Proto: Proto::BaseEBBoxData< cent, data_t, ncomp > Class Template Reference
Proto::BaseEBBoxData< cent, data_t, ncomp > Class Template Reference
#include <Proto_EBBoxData.H>
Public Member Functions
BaseEBBoxData ()
virtual ~BaseEBBoxData ()
virtual void setVal (data_t a_val)
data_t operator() (const EBIndex< cent > &a_vof, unsigned int a_c) const
will not work on device–debugging use only
const data_t * dataPtr (int a_dataType, int a_ivar) const
for AggStencil
data_t * dataPtr (int a_dataType, int a_ivar)
for AggStencil
BoxData< data_t, ncomp > & getRegData ()
needed to apply stencils
const BoxData< data_t, ncomp > & getRegData () const
needed to apply stencils
IrregData< cent, data_t, ncomp > & getIrregData ()
needed to apply stencils
const IrregData< cent, data_t,
ncomp > & getIrregData () const
needed to apply stencils
BaseEBBoxData (const Box &a_box, bool a_stackAlloc)
needed for Proto::LevelData. meaningless here becasue we need the graph.
void define (const Box &a_box, const EBGraph &a_graph)
void dataInfo (data_t *&a_dataPtr, size_t &a_datasize, unsigned int a_whichfab)
for data transfers. datasize does NOT include sizeof(data_t) (to conform with boxdata::size)
Box box () const
EBGraph ebgraph () const
Protected Member Functions
BaseEBBoxData (const BaseEBBoxData< cent, data_t, ncomp > &a_src)
BaseEBBoxData & operator= (const BaseEBBoxData< cent, data_t, ncomp > &a_src)
Protected Attributes
EBGraph m_graph
PointSet m_irreg
BoxData< data_t, ncomp > m_regData
IrregData< cent, data_t, ncomp > m_irrData
Constructor & Destructor Documentation
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::BaseEBBoxData< cent, data_t, ncomp >::BaseEBBoxData () inline
template<CENTERING cent, typename data_t, unsigned int ncomp> virtual Proto::BaseEBBoxData< cent, data_t, ncomp >::~BaseEBBoxData () inline virtual
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::BaseEBBoxData< cent, data_t, ncomp >::BaseEBBoxData (const Box & a_box, bool a_stackAlloc) inline
needed for Proto::LevelData. meaningless here becasue we need the graph.
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::BaseEBBoxData< cent, data_t, ncomp >::BaseEBBoxData (const BaseEBBoxData< cent, data_t, ncomp > & a_src) protected
Member Function Documentation
template<CENTERING cent, typename data_t, unsigned int ncomp> virtual void Proto::BaseEBBoxData< cent, data_t, ncomp >::setVal (data_t a_val) inline virtual
References Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irrData, Proto::BaseEBBoxData< cent, data_t, ncomp >::m_regData, and Proto::BoxData< T, C, D, E >::setVal().
template<CENTERING cent, typename data_t, unsigned int ncomp> data_t Proto::BaseEBBoxData< cent, data_t, ncomp >::operator() (const EBIndex< cent > & a_vof, unsigned int a_c) const inline
will not work on device–debugging use only
References Proto::EBGraph::isIrregular(), Proto::BaseEBBoxData< cent, data_t, ncomp >::m_graph, Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irrData, Proto::EBIndex< cent >::m_pt, and Proto::BaseEBBoxData< cent, data_t, ncomp >::m_regData.
template<CENTERING cent, typename data_t, unsigned int ncomp> const data_t* Proto::BaseEBBoxData< cent, data_t, ncomp >::dataPtr (int a_dataType, int a_ivar) const inline
for AggStencil
References Proto::BoxData< T, C, D, E >::dataPtr(), Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irrData, and Proto::BaseEBBoxData< cent, data_t, ncomp >::m_regData.
template<CENTERING cent, typename data_t, unsigned int ncomp> data_t* Proto::BaseEBBoxData< cent, data_t, ncomp >::dataPtr (int a_dataType, int a_ivar) inline
for AggStencil
References Proto::BoxData< T, C, D, E >::dataPtr(), Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irrData, and Proto::BaseEBBoxData< cent, data_t, ncomp >::m_regData.
template<CENTERING cent, typename data_t, unsigned int ncomp> BoxData<data_t,ncomp>& Proto::BaseEBBoxData< cent, data_t, ncomp >::getRegData () inline
needed to apply stencils
References Proto::BaseEBBoxData< cent, data_t, ncomp >::m_regData.
template<CENTERING cent, typename data_t, unsigned int ncomp> const BoxData<data_t,ncomp>& Proto::BaseEBBoxData< cent, data_t, ncomp >::getRegData () const inline
needed to apply stencils
References Proto::BaseEBBoxData< cent, data_t, ncomp >::m_regData.
template<CENTERING cent, typename data_t, unsigned int ncomp> IrregData<cent, data_t,ncomp>& Proto::BaseEBBoxData< cent, data_t, ncomp >::getIrregData () inline
needed to apply stencils
References Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irrData.
template<CENTERING cent, typename data_t, unsigned int ncomp> const IrregData<cent, data_t, ncomp>& Proto::BaseEBBoxData< cent, data_t, ncomp >::getIrregData () const inline
needed to apply stencils
References Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irrData.
template<CENTERING cent, typename data_t, unsigned int ncomp> void Proto::BaseEBBoxData< cent, data_t, ncomp >::define (const Box & a_box, const EBGraph & a_graph) inline
References Proto::BoxData< T, C, D, E >::define(), Proto::EBGraph::getIrregCells(), Proto::BaseEBBoxData< cent, data_t, ncomp >::m_graph, Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irrData, Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irreg, and Proto::BaseEBBoxData< cent, data_t, ncomp >::m_regData.
template<CENTERING cent, typename data_t, unsigned int ncomp> void Proto::BaseEBBoxData< cent, data_t, ncomp >::dataInfo (data_t *& a_dataPtr, size_t & a_datasize, unsigned int a_whichfab) inline
for data transfers. datasize does NOT include sizeof(data_t) (to conform with boxdata::size)
References Proto::BoxData< T, C, D, E >::data(), Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irrData, Proto::BaseEBBoxData< cent, data_t, ncomp >::m_regData, PR_assert, and Proto::BoxData< T, C, D, E >::size().
template<CENTERING cent, typename data_t, unsigned int ncomp> Box Proto::BaseEBBoxData< cent, data_t, ncomp >::box () const inline
References Proto::BoxData< T, C, D, E >::box(), and Proto::BaseEBBoxData< cent, data_t, ncomp >::m_regData.
template<CENTERING cent, typename data_t, unsigned int ncomp> EBGraph Proto::BaseEBBoxData< cent, data_t, ncomp >::ebgraph () const inline
References Proto::BaseEBBoxData< cent, data_t, ncomp >::m_graph.
template<CENTERING cent, typename data_t, unsigned int ncomp> BaseEBBoxData& Proto::BaseEBBoxData< cent, data_t, ncomp >::operator= (const BaseEBBoxData< cent, data_t, ncomp > & a_src) protected
Member Data Documentation
template<CENTERING cent, typename data_t, unsigned int ncomp> EBGraph Proto::BaseEBBoxData< cent, data_t, ncomp >::m_graph protected
Referenced by Proto::BaseEBBoxData< cent, data_t, ncomp >::define(), Proto::BaseEBBoxData< cent, data_t, ncomp >::ebgraph(), and Proto::BaseEBBoxData< cent, data_t, ncomp >::operator()().
template<CENTERING cent, typename data_t, unsigned int ncomp> PointSet Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irreg protected
Referenced by Proto::BaseEBBoxData< cent, data_t, ncomp >::define().
template<CENTERING cent, typename data_t, unsigned int ncomp> BoxData< data_t, ncomp> Proto::BaseEBBoxData< cent, data_t, ncomp >::m_regData protected
Referenced by Proto::BaseEBBoxData< cent, data_t, ncomp >::box(), Proto::BaseEBBoxData< cent, data_t, ncomp >::dataInfo(), Proto::BaseEBBoxData< cent, data_t, ncomp >::dataPtr(), Proto::BaseEBBoxData< cent, data_t, ncomp >::define(), Proto::BaseEBBoxData< cent, data_t, ncomp >::getRegData(), Proto::BaseEBBoxData< cent, data_t, ncomp >::operator()(), and Proto::BaseEBBoxData< cent, data_t, ncomp >::setVal().
template<CENTERING cent, typename data_t, unsigned int ncomp> IrregData<cent, data_t, ncomp> Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irrData protected
Referenced by Proto::BaseEBBoxData< cent, data_t, ncomp >::dataInfo(), Proto::BaseEBBoxData< cent, data_t, ncomp >::dataPtr(), Proto::BaseEBBoxData< cent, data_t, ncomp >::define(), Proto::BaseEBBoxData< cent, data_t, ncomp >::getIrregData(), Proto::BaseEBBoxData< cent, data_t, ncomp >::operator()(), and Proto::BaseEBBoxData< cent, data_t, ncomp >::setVal().
The documentation for this class was generated from the following file:
Proto_EBBoxData.H