Proto: Proto::CInterval Class Reference
Proto::CInterval Class Reference
Pointwise Operations
Component-Space Interval.
#include <Proto_BoxData.H>
Public Member Functions
CInterval (unsigned int a_c0, unsigned int a_c1, unsigned int a_d0=0, unsigned int a_d1=0, unsigned int a_e0=0, unsigned int a_e1=0)
Bounds Constructor.
CInterval (std::initializer_list< std::initializer_list< unsigned int >> a_lst)
List Constructor.
unsigned int low (unsigned int a_comp) const
Lower Bound.
unsigned int high (unsigned int a_comp) const
Upper Bound.
bool contains (unsigned int a_index, unsigned int a_comp) const
Contains Query.
unsigned int size (unsigned int a_comp) const
Size Query.
void print () const
Print.
Private Attributes
unsigned int m_comps [3][2]
bounds of the interval
Detailed Description
Component-Space Interval.
Defines a subspace of tensor components. Used chiefly for copying and and linearized buffer IO. Usually the user will not need to explicitly create a CInterval. See the documentation for BoxData::copyTo for an example.
Constructor & Destructor Documentation
Proto::CInterval::CInterval (unsigned int a_c0, unsigned int a_c1, unsigned int a_d0 = 0, unsigned int a_d1 = 0, unsigned int a_e0 = 0, unsigned int a_e1 = 0) inline
Bounds Constructor.
Builds the interval: {{a_c0, a_c1},{a_d0, a_d1},{a_e0, a_e1}}
References PROTO_ASSERT.
Proto::CInterval::CInterval (std::initializer_list< std::initializer_list< unsigned int >> a_lst) inline
List Constructor.
Build a CInterval using the syntax:
CInterval I0{{c0, c1},{d0, d1},{e0, e1}};
// OR
CInterval I1({{c0, c1},{d0, d1},{e0, e1}});
// Or, for a single component index:
CInterval I2{c0, c1};
// OR
CInterval I3({c0, c1});
// OR
Member Function Documentation
unsigned int Proto::CInterval::low (unsigned int a_comp) const inline
Lower Bound.
Retrieve the lower bound along the given component axis
Referenced by Proto::operator<<().
unsigned int Proto::CInterval::high (unsigned int a_comp) const inline
Upper Bound.
Retrieve the upper bound component for component axis a_comp
References PROTO_ASSERT.
Referenced by Proto::BoxData< T, C, D, E >::contains(), and Proto::operator<<().
bool Proto::CInterval::contains (unsigned int a_index, unsigned int a_comp) const inline
Contains Query.
Query if *this contains index of component comp
References m_comps, and PROTO_ASSERT.
unsigned int Proto::CInterval::size (unsigned int a_comp) const inline
Size Query.
Returns the number of components in *this along the component axis a_comp
void Proto::CInterval::print () const inline
Print.
References m_comps.
Member Data Documentation
unsigned int Proto::CInterval::m_comps[3][2] private
bounds of the interval
Referenced by Proto::BoxData< T, C, D, E >::BoxData(), contains(), Proto::BoxData< T, C, D, E >::defineMalloc(), and print().
The documentation for this class was generated from the following file:
Proto_BoxData.H