Proto: Proto::GeometryService< order > Class Template Reference
Proto::GeometryService< order > Class Template Reference
Makes geometric description from an implicit function.
#include <Proto_GeometryService.H>
Public Types
typedef IndexedMoments< DIM,
order > IndMomDIM
typedef IndexedMoments< DIM-1,
order > IndMomSDMinOne
typedef MomentIterator< DIM,
order > MomItDIM
typedef MomentIterator< DIM-1,
order > MomItSDMinOne
typedef IrregNode< order > inode
typedef HostIrregData< CELL,
IndMomDIM, 1 > VoluData
typedef HostIrregData
< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE,
IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE,
IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE,
IndMomSDMinOne, 1 > ZFacData
Public Member Functions
GeometryService (const shared_ptr< BaseIF > &a_baseIF, const RealVect &a_origin, const double &a_dx, const Box &a_domain, const DisjointBoxLayout &a_finestGrids, const Point &a_ghost, int a_maxCoarsen)
void fillGraph (HostBoxData< int > &a_regIrregCovered, vector< inode > &a_nodes, const Box &a_validRegion, const Box &a_ghostRegion, const Box &a_domain) const
int getLevel (const Box &a_domain)
shared_ptr< LevelData< EBGraph > > getGraphs (const Box &a_domain)
shared_ptr< LevelData< VoluData > > getVoluData (const Box &a_domain)
shared_ptr< LevelData< EBFaData > > getEBFaceData (const Box &a_domain)
shared_ptr< LevelData< XFacData > > getXFaceData (const Box &a_domain)
shared_ptr< LevelData< YFacData > > getYFaceData (const Box &a_domain)
shared_ptr< LevelData< ZFacData > > getZFaceData (const Box &a_domain)
Protected Member Functions
void defineFinestLevel (const RealVect &a_origin, const double &a_dx)
bool onBoxBoundary (const Point &a_iv, const Box &a_box, const int &a_dir, const Side::LoHiSide &a_sd) const
RealVect convert2RelativeCoord (const RealVect &a_rVect) const
RealVect convert2RelativeCoord (const IndexTM< double, DIM > &a_rVect) const
void fillNewNode (inode &a_node, const PointSet &a_ivsIrreg, const Point &a_iv) const
shared_ptr< BaseIF > getBaseIF () const
Private Member Functions
void fixRegularCellsNextToCovered (vector< inode > &a_nodes, HostBoxData< int > &a_regIrregCovered, const Box &a_validRegion, const Point &a_iv) const
void getFullNodeWithCoveredFace (inode &a_newNode, const HostBoxData< int > &a_regIrregCovered, const Point &a_iv) const
void fillArc (vector< int > a_arc[DIM], CutCellMoments< DIM > &a_cutCellMoments, const int &a_hilo, const PointSet &a_ivsIrreg, const Point &a_curriv) const
GeometryService ()
GeometryService (const GeometryService &a_workshopin)
void operator= (const GeometryService &a_workshopin)
Private Attributes
vector< Box > m_domains
these vectors are of the length of number of coarsenings
vector< DisjointBoxLayout > m_grids
vector< shared_ptr< LevelData
< EBGraph > > > m_graphs
vector< shared_ptr< LevelData
< VoluData > > > m_voludata
vector< shared_ptr< LevelData
< EBFaData > > > m_ebfadata
vector< shared_ptr< LevelData
< XFacData > > > m_xfacdata
vector< shared_ptr< LevelData
< YFacData > > > m_yfacdata
vector< shared_ptr< LevelData
< ZFacData > > > m_zfacdata
double m_threshold
RealVect m_origin
int m_order
int m_degreeP
double m_dx
Box m_domain
Point m_geomgrow
shared_ptr< BaseIF > m_baseIF
Detailed Description
template<int order>
class Proto::GeometryService< order >
Makes geometric description from an implicit function.
Given an implicit function and grid information, this cuts the grids and provides moments.
Member Typedef Documentation
template<int order> typedef IndexedMoments<DIM , order> Proto::GeometryService< order >::IndMomDIM
template<int order> typedef IndexedMoments<DIM-1, order> Proto::GeometryService< order >::IndMomSDMinOne
template<int order> typedef MomentIterator<DIM , order> Proto::GeometryService< order >::MomItDIM
template<int order> typedef MomentIterator<DIM-1, order> Proto::GeometryService< order >::MomItSDMinOne
template<int order> typedef IrregNode<order> Proto::GeometryService< order >::inode
template<int order> typedef HostIrregData<CELL , IndMomDIM , 1> Proto::GeometryService< order >::VoluData
template<int order> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::GeometryService< order >::EBFaData
template<int order> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::GeometryService< order >::XFacData
template<int order> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::GeometryService< order >::YFacData
template<int order> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::GeometryService< order >::ZFacData
Constructor & Destructor Documentation
template<int order> Proto::GeometryService< order >::GeometryService (const shared_ptr< BaseIF > & a_baseIF, const RealVect & a_origin, const double & a_dx, const Box & a_domain, const DisjointBoxLayout & a_finestGrids, const Point & a_ghost, int a_maxCoarsen)
basif : implicit function origin : location of the lower left corner of the domain dx : grid spacing domain : finest domain in the calculation finestGrids: layout of the finest domain ghost : maximum number of ghost cells needed in calculation maxCoarsen : maximum level of coarsening
template<int order> Proto::GeometryService< order >::GeometryService () private
template<int order> Proto::GeometryService< order >::GeometryService (const GeometryService< order > & a_workshopin) private
Member Function Documentation
template<int order> void Proto::GeometryService< order >::fillGraph (HostBoxData< int > & a_regIrregCovered, vector< inode > & a_nodes, const Box & a_validRegion, const Box & a_ghostRegion, const Box & a_domain) const inline
Define the internals of the input ebisRegion. Public for testing.
template<int order> int Proto::GeometryService< order >::getLevel (const Box & a_domain) inline
References Proto::GeometryService< order >::m_domains, and PROTO_ASSERT.
Referenced by Proto::GeometryService< order >::getEBFaceData(), Proto::GeometryService< order >::getGraphs(), Proto::GeometryService< order >::getVoluData(), Proto::GeometryService< order >::getXFaceData(), Proto::GeometryService< order >::getYFaceData(), and Proto::GeometryService< order >::getZFaceData().
template<int order> shared_ptr<LevelData<EBGraph> > Proto::GeometryService< order >::getGraphs (const Box & a_domain) inline
References Proto::GeometryService< order >::getLevel(), and Proto::GeometryService< order >::m_graphs.
template<int order> shared_ptr<LevelData<VoluData> > Proto::GeometryService< order >::getVoluData (const Box & a_domain) inline
References Proto::GeometryService< order >::getLevel(), and Proto::GeometryService< order >::m_voludata.
template<int order> shared_ptr<LevelData<EBFaData> > Proto::GeometryService< order >::getEBFaceData (const Box & a_domain) inline
References Proto::GeometryService< order >::getLevel(), and Proto::GeometryService< order >::m_ebfadata.
template<int order> shared_ptr<LevelData<XFacData> > Proto::GeometryService< order >::getXFaceData (const Box & a_domain) inline
References Proto::GeometryService< order >::getLevel(), and Proto::GeometryService< order >::m_xfacdata.
template<int order> shared_ptr<LevelData<YFacData> > Proto::GeometryService< order >::getYFaceData (const Box & a_domain) inline
References Proto::GeometryService< order >::getLevel(), and Proto::GeometryService< order >::m_yfacdata.
template<int order> shared_ptr<LevelData<ZFacData> > Proto::GeometryService< order >::getZFaceData (const Box & a_domain) inline
References Proto::GeometryService< order >::getLevel(), and Proto::GeometryService< order >::m_zfacdata.
template<int order> void Proto::GeometryService< order >::defineFinestLevel (const RealVect & a_origin, const double & a_dx) protected
template<int order> bool Proto::GeometryService< order >::onBoxBoundary (const Point & a_iv, const Box & a_box, const int & a_dir, const Side::LoHiSide & a_sd) const protected
template<int order> RealVect Proto::GeometryService< order >::convert2RelativeCoord (const RealVect & a_rVect) const inline protected
template<int order> RealVect Proto::GeometryService< order >::convert2RelativeCoord (const IndexTM< double, DIM > & a_rVect) const inline protected
template<int order> void Proto::GeometryService< order >::fillNewNode (inode & a_node, const PointSet & a_ivsIrreg, const Point & a_iv) const inline protected
template<int order> shared_ptr<BaseIF> Proto::GeometryService< order >::getBaseIF () const inline protected
References Proto::GeometryService< order >::m_baseIF.
template<int order> void Proto::GeometryService< order >::fixRegularCellsNextToCovered (vector< inode > & a_nodes, HostBoxData< int > & a_regIrregCovered, const Box & a_validRegion, const Point & a_iv) const inline private
template<int order> void Proto::GeometryService< order >::getFullNodeWithCoveredFace (inode & a_newNode, const HostBoxData< int > & a_regIrregCovered, const Point & a_iv) const inline private
template<int order> void Proto::GeometryService< order >::fillArc (vector< int > a_arc[DIM], CutCellMoments< DIM > & a_cutCellMoments, const int & a_hilo, const PointSet & a_ivsIrreg, const Point & a_curriv) const inline private
template<int order> void Proto::GeometryService< order >::operator= (const GeometryService< order > & a_workshopin) private
Member Data Documentation
template<int order> vector<Box> Proto::GeometryService< order >::m_domains private
these vectors are of the length of number of coarsenings
Referenced by Proto::GeometryService< order >::getLevel().
template<int order> vector<DisjointBoxLayout> Proto::GeometryService< order >::m_grids private
template<int order> vector<shared_ptr<LevelData<EBGraph> > > Proto::GeometryService< order >::m_graphs private
Referenced by Proto::GeometryService< order >::getGraphs().
template<int order> vector<shared_ptr<LevelData<VoluData> > > Proto::GeometryService< order >::m_voludata private
Referenced by Proto::GeometryService< order >::getVoluData().
template<int order> vector<shared_ptr<LevelData<EBFaData> > > Proto::GeometryService< order >::m_ebfadata private
Referenced by Proto::GeometryService< order >::getEBFaceData().
template<int order> vector<shared_ptr<LevelData<XFacData> > > Proto::GeometryService< order >::m_xfacdata private
Referenced by Proto::GeometryService< order >::getXFaceData().
template<int order> vector<shared_ptr<LevelData<YFacData> > > Proto::GeometryService< order >::m_yfacdata private
Referenced by Proto::GeometryService< order >::getYFaceData().
template<int order> vector<shared_ptr<LevelData<ZFacData> > > Proto::GeometryService< order >::m_zfacdata private
Referenced by Proto::GeometryService< order >::getZFaceData().
template<int order> double Proto::GeometryService< order >::m_threshold private
template<int order> RealVect Proto::GeometryService< order >::m_origin private
template<int order> int Proto::GeometryService< order >::m_order private
template<int order> int Proto::GeometryService< order >::m_degreeP private
template<int order> double Proto::GeometryService< order >::m_dx private
template<int order> Box Proto::GeometryService< order >::m_domain private
template<int order> Point Proto::GeometryService< order >::m_geomgrow private
template<int order> shared_ptr<BaseIF> Proto::GeometryService< order >::m_baseIF private
Referenced by Proto::GeometryService< order >::getBaseIF().
The documentation for this class was generated from the following file:
Proto_GeometryService.H