Proto: Proto::SimpleGeometry Class Reference
Proto::SimpleGeometry Class Reference
truly simple geometries can have some simplified bits about what is all covered or regular
#include <Proto_SimpleImplicitFunctions.H>
Public Member Functions
IndexTM< double, DIM > getIndexTM (const RealVect &a_rv)
vector< RealVect > getCornerLocations (const Box &a_box, const RealVect &a_origin, const double &a_dx)
Public Member Functions inherited from Proto::BaseIF
BaseIF ()
Default constructor.
virtual ~BaseIF ()
Default destructor.
virtual double value (const IndexTM< int, DIM > &a_partialDerivative, const IndexTM< double, DIM > &a_point) const =0
virtual bool entireBoxRegular (const Box &a_box, const RealVect &a_origin, const double &a_dx)
virtual bool entireBoxCovered (const Box &a_box, const RealVect &a_origin, const double &a_dx)
overwrite if you have a fast way of knowing if a whole region is regular
virtual BaseIF * newImplicitFunction () const =0
factory method
Detailed Description
truly simple geometries can have some simplified bits about what is all covered or regular
For simple geometries, this provides an easy way to encapsulate the writing of a BaseIF
Member Function Documentation
IndexTM<double,DIM> Proto::SimpleGeometry::getIndexTM (const RealVect & a_rv) inline
Referenced by Proto::SimpleEllipsoidIF::entireBoxCovered(), Proto::PlaneIF::entireBoxCovered(), Proto::SimpleEllipsoidIF::entireBoxRegular(), and Proto::PlaneIF::entireBoxRegular().
vector<RealVect> Proto::SimpleGeometry::getCornerLocations (const Box & a_box, const RealVect & a_origin, const double & a_dx) inline
References Proto::Box::high(), Proto::Box::low(), and Proto::Point::Ones().
Referenced by Proto::SimpleEllipsoidIF::entireBoxCovered(), Proto::PlaneIF::entireBoxCovered(), Proto::SimpleEllipsoidIF::entireBoxRegular(), and Proto::PlaneIF::entireBoxRegular().
The documentation for this class was generated from the following file:
Proto_SimpleImplicitFunctions.H