Proto: Proto::Point Class Reference
Proto::Point Class Reference
Integer Valued Vector.
#include <Proto_Point.H>
Public Member Functions
template<>
void unpack (int D, int i)
Constructors
CUDA_DECORATION Point ()
CUDA_DECORATION Point (const int(&a_tuple)[DIM])
C Array Constructor.
template<typename... vals>
CUDA_DECORATION Point (vals...args)
Variadic Constructor.
CUDA_DECORATION Point (const Point &a_pt)
Copy Constructor.
Accessors
CUDA_DECORATION const int & operator[] (unsigned char a_index) const
Get Component (Const)
CUDA_DECORATION int & operator[] (unsigned char a_index)
Get Component (Non-Const)
Operators
CUDA_DECORATION Point & operator= (const Point &a_rhs)
Equals Operator.
CUDA_DECORATION bool operator< (const Point &a_rhs) const
Less-Than Operator.
CUDA_DECORATION bool operator== (const Point &a_pt) const
Equality Operator.
CUDA_DECORATION bool operator!= (const Point &a_pt) const
Inequality Operator.
CUDA_DECORATION Point operator+ (const Point &a_rhs) const
Componentwise Point Addition Operator.
CUDA_DECORATION Point operator- (const Point &a_rhs) const
Componentwise Point Subtraction Operator.
CUDA_DECORATION Point operator* (const Point &a_pt) const
Componentwise Point Multiplication Operator.
CUDA_DECORATION Point operator/ (const Point &a_pt) const
Componentwise Point Division Operator.
CUDA_DECORATION Point operator% (const Point &a_pt) const
Componentwise Point Modulus Operator.
Point operator+ (int a_nref) const
Scalar Addition Operator.
Point operator- (int a_nref) const
Scalar Subtraction Operator.
Point operator* (int a_nref) const
Scalar Multiplication Operator.
Point operator/ (int a_nref) const
Scalar Division Operator.
Point operator% (int a_nref) const
Scalar Modulus Operator.
CUDA_DECORATION void operator+= (const Point &a_pt)
In Place Componentwise Addition Operator.
CUDA_DECORATION void operator-= (const Point &a_pt)
In Place Componentwise Subtraction Operator.
CUDA_DECORATION void operator*= (const Point &a_pt)
In Place Componentwise Multiplication Operator.
CUDA_DECORATION void operator/= (const Point &a_pt)
In Place Componentwise Division Operator.
CUDA_DECORATION void operator%= (const Point &a_pt)
In Place Componentwise Modulus Operator.
void operator+= (int a_n)
In Place Scalar Addition Operator.
void operator-= (int a_n)
In Place Scalar Subtraction Operator.
void operator*= (int a_n)
In Place Scalar Multiplication Operator.
void operator/= (int a_n)
In Place Scalar Division Operator.
void operator%= (int a_n)
In Place Scalar Modulus Operator.
int sum ()
Computes the sum of the entries in *this.
int absSum ()
Computes the sum of the absolute values of the entries in *this.
Utility
void print () const
Print Function.
Public Attributes
int m_tuple [DIM]
Integer coordinates of the Point.
Private Member Functions
template<typename... vars>
CUDA_DECORATION void unpack (int D, int i, vars...args)
Static Methods
int sum () const
Point coarsen (unsigned int a_refRat) const
static Point Basis (int a_dir, int a_scale=1)
Get Basis.
static Point Zeros ()
Get Zeros.
static Point Zeroes ()
Get Zeros (if you like spelling things correctly)
static Point Zero ()
static Point Unit ()
static Point Ones (int a_scale=1)
Get Ones.
Detailed Description
Integer Valued Vector.
An element of
Constructor & Destructor Documentation
Proto::Point::Point () inline
Default Constructor Returns the zero Point (0,0,...,0)
Proto::Point::Point (const int(&) a_tuple[DIM]) inline
C Array Constructor.
Allows "literal" construction of points.
Example:
using namespace Proto;
//DIM=2
Point p = Point({-5,13}); //creates the point (-5,13)
Parameters
a_tuple integer array representing a Point
template<typename... vals> CUDA_DECORATION Proto::Point::Point (vals... args) inline explicit
Variadic Constructor.
Builds a Point from the first DIM arguments given to this. Any trailing arguments are ignored. This constructor is very useful for building dimensionally independent test code.
Example:
Point p(1,2,3,4,5,6);
if (DIM == 1)
{
std::cout << p << std::endl;    //prints (1)
} else if (DIM == 2) {
std::cout << p << std::endl;    //prints (1, 2)
} else if (DIM == 3) {
std::cout << p << std::endl;    //prints (1, 2, 3)
} //etc.
Parameters
args at least DIM integer arguments representing a Point
Proto::Point::Point (const Point & a_pt) inline
Copy Constructor.
Member Function Documentation
Point Proto::Point::Basis (int a_dir, int a_scale = 1) inline static
Get Basis.
Returns an axis-aligned Point .
Parameters
a_dir A spatial axis (0 for x, 1 for y, etc.)
a_scale (Optional) value to scale the unit vector by (default: no scaling)
Referenced by Proto::Box::grow(), Proto::Box::growHi(), Proto::Box::growLo(), and Proto::Stencil< T >::operator*=().
int Proto::Point::sum () const inline
Point Proto::Point::Zeros () inline static
Get Zeros.
Returns the zero Point (0,0,...,0)
Referenced by Zero(), and Proto::Shift::Zeros().
static Point Proto::Point::Zeroes () inline static
Get Zeros (if you like spelling things correctly)
Returns the zero Point (0,0,...,0)
Referenced by Proto::Stencil< double >::diagonalValue().
static Point Proto::Point::Zero () inline static
References Zeros().
static Point Proto::Point::Unit () inline static
References Ones().
Point Proto::Point::coarsen (unsigned int a_refRat) const inline
Point Proto::Point::Ones (int a_scale = 1) inline static
Get Ones.
Returns the unit Point scale*(1,1,...,1)
Parameters
a_scale (Optional) value to scale the vector by (default: no scaling)
Referenced by Proto::InterpStencil< T >::close(), Proto::Box::coarsenable(), Proto::InterpStencil< T >::define(), Proto::SimpleGeometry::getCornerLocations(), Proto::InterpStencil< T >::InterpStencil(), Proto::Shift::Ones(), and Unit().
CUDA_DECORATION const int& Proto::Point::operator[] (unsigned char a_index) const inline
Get Component (Const)
Returns a const reference to the a_index component of *this
Parameters
a_index Index in [0,DIM)
References m_tuple, and PROTO_ASSERT.
CUDA_DECORATION int& Proto::Point::operator[] (unsigned char a_index) inline
Get Component (Non-Const)
Returns a mutable reference to the a_index component of *this
Parameters
a_index Index in [0,DIM)
References PROTO_ASSERT.
Point & Proto::Point::operator= (const Point & a_rhs) inline
Equals Operator.
Equality is based on value, not instance.
Parameters
a_rhs Another Point
bool Proto::Point::operator< (const Point & a_rhs) const inline
Less-Than Operator.
Used to define an ordering for placing Points in maps etc. Do not use to actually compare Points. Uses Lexical comparison. Note that Chombo lexLT is also lexical but uses the dimensions in the opposite way. Both work for maps and so on.
Parameters
a_rhs Another Point
bool Proto::Point::operator== (const Point & a_pt) const inline
Equality Operator.
Returns true if: this[ ] == *a_pt[ ]
Parameters
a_pt Another Point
bool Proto::Point::operator!= (const Point & a_pt) const inline
Inequality Operator.
Returns true if *this != a_pt.
Parameters
a_pt Another Point
Point Proto::Point::operator+ (const Point & a_rhs) const inline
Componentwise Point Addition Operator.
Creates the new Point by adding *this and rhs componentwise.
Parameters
a_rhs Another Point
Point Proto::Point::operator- (const Point & a_rhs) const inline
Componentwise Point Subtraction Operator.
Creates the new Point by subtracting *this and rhs componentwise.
Parameters
a_rhs Another Point
Point Proto::Point::operator* (const Point & a_pt) const inline
Componentwise Point Multiplication Operator.
Creates the new Point by multiplying *this and rhs componentwise.
Parameters
a_pt Another Point
Point Proto::Point::operator/ (const Point & a_pt) const inline
Componentwise Point Division Operator.
Creates the new Point by dividing *this by rhs componentwise. Quotients are rounded down. Division of any component by 0 yields an error.
Parameters
a_pt Another Point
Point Proto::Point::operator% (const Point & a_pt) const inline
Componentwise Point Modulus Operator.
Creates the new Point by taking the modulus of *this by rhs componentwise. Quotients are rounded down. Modulo by 0 yields an error.
Parameters
a_pt Another Point
Point Proto::Point::operator+ (int a_nref) const inline
Scalar Addition Operator.
Creates a new point by adding nref to each component of *this.
Parameters
a_nref An Integer scalar
Point Proto::Point::operator- (int a_nref) const inline
Scalar Subtraction Operator.
Creates a new point by subtracting nref to each component of *this.
Parameters
a_nref An Integer scalar
Point Proto::Point::operator* (int a_nref) const inline
Scalar Multiplication Operator.
Creates a new point by multiplying each component of *this by nref.
Parameters
a_nref An Integer scalar
Point Proto::Point::operator/ (int a_nref) const inline
Scalar Division Operator.
Creates a new point by dividing each component of *this by nref. Quotients are rounded down. Division of any component by 0 yields an error.
Parameters
a_nref An Integer scalar
Point Proto::Point::operator% (int a_nref) const inline
Scalar Modulus Operator.
Creates a new point by taking the modulus of each component of *this by nref. Quotients are rounded down. Modulo of any component by 0 yields an error.
Parameters
a_nref An Integer scalar
void Proto::Point::operator+= (const Point & a_pt) inline
In Place Componentwise Addition Operator.
void Proto::Point::operator-= (const Point & a_pt) inline
In Place Componentwise Subtraction Operator.
void Proto::Point::operator*= (const Point & a_pt) inline
In Place Componentwise Multiplication Operator.
void Proto::Point::operator/= (const Point & a_pt) inline
In Place Componentwise Division Operator.
Quotients are rounded down. Division of any component by 0 yields an error.
Parameters
a_pt Another Point
void Proto::Point::operator%= (const Point & a_pt) inline
In Place Componentwise Modulus Operator.
void Proto::Point::operator+= (int a_n) inline
In Place Scalar Addition Operator.
void Proto::Point::operator-= (int a_n) inline
In Place Scalar Subtraction Operator.
void Proto::Point::operator*= (int a_n) inline
In Place Scalar Multiplication Operator.
void Proto::Point::operator/= (int a_n) inline
In Place Scalar Division Operator.
Quotients are rounded down. Division of any component by 0 yields an error.
void Proto::Point::operator%= (int a_n) inline
In Place Scalar Modulus Operator.
int Proto::Point::sum () inline
Computes the sum of the entries in *this.
References m_tuple.
int Proto::Point::absSum () inline
Computes the sum of the absolute values of the entries in *this.
References m_tuple.
void Proto::Point::print () const inline
Print Function.
Output is formatted: (p1,p2,...)
References m_tuple.
template<typename... vars> CUDA_DECORATION void Proto::Point::unpack (int D, int i, vars... args) inline private
References m_tuple.
template<> void Proto::Point::unpack (int D, int i) inline
References m_tuple.
Member Data Documentation
int Proto::Point::m_tuple[DIM]
Integer coordinates of the Point.
Referenced by absSum(), operator[](), print(), sum(), and unpack().
The documentation for this class was generated from the following file:
Proto_Point.H