Proto: Proto::BoxData< T, C, D, E > Class Template Reference
Proto::BoxData< T, C, D, E > Class Template Reference
Pointwise Operations | Stencil Operations
Multidimensional Rectangular Array.
#include <Proto_BoxData.H>
Public Types
typedef Var< T, C, D, E > reference
typedef BoxData< double, 1, 1, 1 > Scalar
Public Member Functions
Constructors and Define
BoxData (const BoxData< T, C, D, E > &a_src)=delete
Copy constructor/assignment forbidden for all the usual reasons.
BoxData & operator= (const BoxData< T, C, D, E > &a_src)=delete
BoxData ()
Default Constructor.
BoxData (const Box &a_box, bool a_stackAllocation=false)
Box Constructor.
BoxData (const Box &a_box, T a_init)
Box Constructor With Initialization.
BoxData (BoxData< T, C, D, E > &&a_src)
Move constructor.
void define (const Box &a_box, bool a_stackAllocation=false)
Box Define.
void defineMalloc (const Box &a_box)
define using malloc instead of stack allocation
void defineStack (const Box &a_box)
define using stack allocation
BoxData (const T *a_ptr, const Box &a_box, int a_ncomp=C)
Raw Pointer Constructor.
void define (const T *a_ptr, const Box &a_box, int a_ncomp=C)
Raw Pointer Define.
BoxData (LazyStencil< T, C, D, E > &&a_op)
LazyStencil Constructor.
BoxData (shared_ptr< T > a_data, const T *a_ptr, const Box &a_box)
Slice Constructor.
~BoxData ()
Destructor.
Data Movement
BoxData & operator= (BoxData< T, C, D, E > &&a_src)
Move Assignment Operator.
void copyTo (BoxData< T, C, D, E > &a_dest) const
Copy on Intersection.
void copyTo (BoxData< T, C, D, E > &a_dest, const Box &a_srcBox, const Point &a_destShift=Point::Zeros()) const
Copy Region.
template<unsigned int Cdest, unsigned char Ddest, unsigned char Edest>
void copyTo (BoxData< T, Cdest, Ddest, Edest > &a_dest, const Box &a_srcBox, CInterval a_srcComps, const Point &a_destShift, CInterval a_destComps) const
General Copy.
template<unsigned int Csrc>
void copy (const BoxData< T, Csrc, D, E > &a_dsrc, const Box &a_srcBox, unsigned int a_srcComp, const Box &a_destBox, unsigned int a_destComp, unsigned int a_numcomp)
General Copy From.
Accessors
CUDA_DECORATION T operator() (const Point &a_pt, unsigned int a_c=0, unsigned char a_d=0, unsigned char a_e=0) const
Read Only Data Accessor.
T * operator[] (unsigned int a_index)
Index Accessor (Non-Const)
const T * operator[] (unsigned int a_index) const
Index Accessor (Const)
const T * data (const Point &a_p, unsigned int a_c=0, unsigned int a_d=0, unsigned int a_e=0) const
Read-Write Accessor (Const)
const T * data () const
T * data (const Point &a_p, unsigned int a_c=0, unsigned int a_d=0, unsigned int a_e=0)
Read-Write Accessor (Non-Const)
T * dataPtr (unsigned int a_c=0, unsigned int a_d=0, unsigned int a_e=0)
const T * dataPtr (unsigned int a_c=0, unsigned int a_d=0, unsigned int a_e=0) const
T * data ()
shared_ptr< T > getData () const
Access Shared Pointer.
CUDA_DECORATION size_t index (const Point a_pt, unsigned int a_c=0, unsigned int a_d=0, unsigned int a_e=0) const
Compute Index.
Box box () const
std::size_t size () const
bool defined () const
Defined Query.
Var< T, C, D, E > var (const Point &a_pt)
Create Pointwise Access Variable (Non-Const)
Var< T, C, D, E > var (const Point &a_pt) const
Create Pointwise Access Variable (Const)
Algebraic Operations
BoxData< T, C, D, E > & operator+= (const BoxData< T, C, D, E > &a_rhs)
Pointwise Addition on Intersection.
BoxData< T, C, D, E > & operator-= (const BoxData< T, C, D, E > &a_rhs)
Pointwise Subtraction on Intersection.
BoxData< T, C, D, E > & operator*= (const BoxData< T, C, D, E > &a_rhs)
Pointwise Multiplication on Intersection.
BoxData< T, C, D, E > & operator/= (const BoxData< T, C, D, E > &a_rhs)
Pointwise Division on Intersection.
BoxData< T, C, D, E > & operator+= (T a_scale)
Pointwise Addition by Scalar.
BoxData< T, C, D, E > & operator-= (T scale)
Pointwise Subtraction by Scalar.
BoxData< T, C, D, E > & operator*= (T scale)
Pointwise Multiplication by Scalar.
BoxData< T, C, D, E > & operator/= (T scale)
Pointwise Division by Scalar.
Utility
void setVal (const T &a_val)
Initialize All Values.
void setVal (const T &a_val, const Box &a_box)
Set All Values in Box.
void setVal (const T &a_val, const Box &a_box, int a_c, int a_d=0, int a_e=0)
Set All Values of Component in Box.
T absMax () const
Absolute Maximum Value (Global)
T absMax (int a_c, int a_d=0, int a_e=0) const
Absolute Maximum Value (Componentwise)
T min () const
Minimum Value (Global)
T min (int a_c, int a_d=0, int a_e=0) const
Minimum Value (Componentwise)
T max () const
Maximum Value (Global)
T max (int a_c, int a_d=0, int a_e=0) const
Maximum Value (Componentwise)
T sum () const
Sum.
T sum (int a_c, int a_d=0, int a_e=0) const
sum (Componentwise)
void shift (const Point a_pt)
Shift Domain.
void linearOut (void *a_buf, const Box &a_box, CInterval a_comps) const
Buffer Write.
template<unsigned int ncomp>
void define (BoxData< T, ncomp > &a_input, unsigned int &a_comp)
void linearIn (void *a_buf, const Box &a_box, CInterval a_comps)
Buffer Read.
bool contains (CInterval a_interval) const
Contains CInterval.
template<unsigned int CC, unsigned char DD, unsigned char EE>
bool isAlias (const BoxData< T, CC, DD, EE > &a_src) const
Check Aliasing.
void print () const
Print.
void printData (int a_prec=2) const
Print Data.
void printData (const Box &a_box, int a_prec=2) const
Print Data in Box.
void printData (const Box &a_box, int a_c, int a_d, int a_e, int a_prec=2) const
Print Component Data in Box.
Private Attributes
bool m_stackAlloc
Box m_box
Box defining the domain of *this.
::std::shared_ptr< T > m_data
Data array.
T * m_rawPtr
Raw pointer to the data.
Friends
template<class TT >
class Stencil
template<class TT , unsigned int CC, unsigned char DD, unsigned char EE>
BoxData< TT, CC, DD, EE > alias (BoxData< TT, CC, DD, EE > &a_original, const Point &a_shift)
template<class TT , unsigned int CC, unsigned char DD, unsigned char EE>
const BoxData< TT, CC, DD, EE > alias (const BoxData< TT, CC, DD, EE > &a_original, const Point &a_shift)
Detailed Description
template<typename T, unsigned int C, unsigned char D, unsigned char E>
class Proto::BoxData< T, C, D, E >
Multidimensional Rectangular Array.
BoxData is the main dataholder class of Proto. It contains an array of data of type T on a domain defined by a Box. Each data point is associated with a Point in the Box. C, D, and E define the tensor structure of the data: C,D,E = 1: Data is scalar (default) C = N, D,E = 1: Data is vector valued with N components C = M, D = N, E = 1: Data is MxN matrix valued
Template Parameters
T Type of data in array (bool, int, double, etc.)
C (Optional) Size of first component axis. Defaults to 1.
D (Optional) Size of second component axis. Defaults to 1.
E (Optional) Size of third component axis. Defaults to 1.
Member Typedef Documentation
template<typename T, unsigned int C, unsigned char D, unsigned char E> typedef Var<T,C,D,E> Proto::BoxData< T, C, D, E >::reference
template<typename T, unsigned int C, unsigned char D, unsigned char E> typedef BoxData<double,1,1,1> Proto::BoxData< T, C, D, E >::Scalar
Constructor & Destructor Documentation
template<typename T, unsigned int C, unsigned char D, unsigned char E> Proto::BoxData< T, C, D, E >::BoxData (const BoxData< T, C, D, E > & a_src) delete
Copy constructor/assignment forbidden for all the usual reasons.
template<class T , unsigned int C, unsigned char D, unsigned char E> Proto::BoxData< T, C, D, E >::BoxData ()
Default Constructor.
Allocates no space; user must call define on resulting object.
template<class T , unsigned int C, unsigned char D, unsigned char E> Proto::BoxData< T, C, D, E >::BoxData (const Box & a_box, bool a_stackAllocation = false)
Box Constructor.
Creates and allocates an uninitialized array based on a Box input.
Parameters
a_box Box defining the domain of *this
template<class T , unsigned int C, unsigned char D, unsigned char E> Proto::BoxData< T, C, D, E >::BoxData (const Box & a_box, T a_init)
Box Constructor With Initialization.
Identical to calling the Box constructor followed by setVal(a_init). Not recommended in performance-critical code if initialization is unnecessary.
Parameters
a_box Box defining the domain of *this
a_init T value used to initialize all data values
template<class T , unsigned int C, unsigned char D, unsigned char E> Proto::BoxData< T, C, D, E >::BoxData (BoxData< T, C, D, E > && a_src)
Move constructor.
Necessary in cases where we return BoxData by value, but don't want an actual deep copy
Parameters
a_src Source data
template<class T , unsigned int C, unsigned char D, unsigned char E> Proto::BoxData< T, C, D, E >::BoxData (const T * a_ptr, const Box & a_box, int a_ncomp = C)
Raw Pointer Constructor.
Builds a vector valued BoxData by aliasing a raw pointer to T which should be of size a_box.size()*a_ncomp . The data in a_ptr is not copied. This constructor is not recommended for public use, but is provided to facilitate compatability with third party libraries.
Parameters
a_ptr Source buffer of type T to which *this will be aliased
a_box Box defining the domain of *this
a_ncomp (Optional) Dummy input for the number of components. Completely unused.
References Proto::CInterval::m_comps, and PROTO_ASSERT.
template<class T , unsigned int C, unsigned char D, unsigned char E> Proto::BoxData< T, C, D, E >::BoxData (LazyStencil< T, C, D, E > && a_op)
LazyStencil Constructor.
Builds a BoxData from a lazily evaluated Stencil operation. Called implicitly.
Parameters
a_op A LazyStencil created by Proto::Stencil::operator() or Proto::InterpStencil::operator()
template<typename T, unsigned int C, unsigned char D, unsigned char E> Proto::BoxData< T, C, D, E >::BoxData (shared_ptr< T > a_data, const T * a_ptr, const Box & a_box)
Slice Constructor.
Used internally. Not part of the public interface.
template<class T , unsigned int C, unsigned char D, unsigned char E> Proto::BoxData< T, C, D, E >::~BoxData ()
Destructor.
Member Function Documentation
template<typename T, unsigned int C, unsigned char D, unsigned char E> BoxData& Proto::BoxData< T, C, D, E >::operator= (const BoxData< T, C, D, E > & a_src) delete
template<class T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::define (const Box & a_box, bool a_stackAllocation = false)
Box Define.
Allocates or reallocates memory for a previously declared BoxData. Any existing data in *this is thrown away.
Parameters
a_box Box defining the domain of *this
template<class T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::defineMalloc (const Box & a_box)
define using malloc instead of stack allocation
References Proto::CInterval::m_comps.
template<class T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::defineStack (const Box & a_box)
define using stack allocation
template<class T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::define (const T * a_ptr, const Box & a_box, int a_ncomp = C)
Raw Pointer Define.
Defines a vector valued BoxData by aliasing a raw pointer to T which should be of size a_box.size()*a_ncomp . The data in a_ptr is not copied. This constructor is not recommended for public use, but is provided to facilitate compatability with third party libraries.
Parameters
a_ptr Source buffer of type T to which *this will be aliased
a_box Box defining the domain of *this
a_ncomp (Optional) Dummy input for the number of components. Completely unused.
template<class T , unsigned int C, unsigned char D, unsigned char E> BoxData< T, C, D, E > & Proto::BoxData< T, C, D, E >::operator= (BoxData< T, C, D, E > && a_src)
Move Assignment Operator.
Moves data in a_src to *this without performing a deep copy.
Parameters
a_src Source Data
template<class T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::copyTo (BoxData< T, C, D, E > & a_dest) const
Copy on Intersection.
Copy data from *this to a_dest within the domain intersection. Does nothing if the domain intersection is empty.
Parameters
a_dest Destination data holder
template<typename T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::copyTo (BoxData< T, C, D, E > & a_dest, const Box & a_srcBox, const Point & a_destShift = Point::Zeros()) const
Copy Region.
Copy with a prescribed Box argument and optional shift. Explicitly, this function copies the subset of data from *this contained in a_srcBox into the region of a_dest defined by a_srcBox.shift(a_destShift) .
This function will fail if a_srcBox is not contained in both this->box() and a_dest.box().shift(a_destShift) .
Parameters
a_dest Destination data holder
a_srcBox Region of data to copy from *this
a_destShift (Optional) Determines region of a_dest to copy data to.
template<typename T , unsigned int C, unsigned char D, unsigned char E> template<unsigned int Cdest, unsigned char Ddest, unsigned char Edest> void Proto::BoxData< T, C, D, E >::copyTo (BoxData< T, Cdest, Ddest, Edest > & a_dest, const Box & a_srcBox, CInterval a_srcComps, const Point & a_destShift, CInterval a_destComps) const
General Copy.
The most general form of copyTo. Copies a prescribed set of components from *this into a_dest within prescribed region with a possible shift.
Example Usage:
Parameters
a_dest Destination data holder
a_srcBox Region of data to copy from *this
a_srcComps Components of *this to copy from
a_destShift Determines region of a_dest to copy data to (e.g. a_srcBox.shift(a_destShift))
a_destComps Components of a_dest to copy into. Must be the same size as a_srcComps.
template<class T , unsigned int C, unsigned char D, unsigned char E> template<unsigned int Csrc> void Proto::BoxData< T, C, D, E >::copy (const BoxData< T, Csrc, D, E > & a_dsrc, const Box & a_srcBox, unsigned int a_srcComp, const Box & a_destBox, unsigned int a_destComp, unsigned int a_numcomp)
General Copy From.
Nearly identical to the most general version of copyTo except the copy direction is reversed. Only valid for vector valued BoxData. This function is provided to facilitate interoperability with third party libraries.
Parameters
a_dsrc Source data
a_srcBox Source domain to copy from
a_srcComp First component to copy from source
a_destBox Destination domain to copy into
a_destComp First component to copy into destiation
a_numcomp Number of components to copy
template<typename T, unsigned int C, unsigned char D, unsigned char E> CUDA_DECORATION T Proto::BoxData< T, C, D, E >::operator() (const Point & a_pt, unsigned int a_c = 0, unsigned char a_d = 0, unsigned char a_e = 0) const inline
Read Only Data Accessor.
debugging only – will not work on the device Read-only access to data stored in *this . This function is read-only to facilitate cross-platform code (e.g. GPU compatability). Pointwise write operations should be done through forall.
Parameters
a_pt A Point in the domain of *this
a_c Value of first tensor index
a_d Value of second tensor index
a_e Value of third tensor index
template<class T , unsigned int C, unsigned char D, unsigned char E> T * Proto::BoxData< T, C, D, E >::operator[] (unsigned int a_index) inline
Index Accessor (Non-Const)
Access *this using a linear index. Useful for interacting with BoxData like a regular buffer, but not recommended.
Parameters
a_index Index in [0,this->size() = m_box.size()*C*D*E)
template<class T , unsigned int C, unsigned char D, unsigned char E> const T * Proto::BoxData< T, C, D, E >::operator[] (unsigned int a_index) const inline
Index Accessor (Const)
Access *this using a linear index. Useful for interacting with BoxData like a regular buffer, but not recommended.
Parameters
a_index Index in [0,this->size() = m_box.size()*C*D*E)
template<typename T, unsigned int C, unsigned char D, unsigned char E> const T* Proto::BoxData< T, C, D, E >::data (const Point & a_p, unsigned int a_c = 0, unsigned int a_d = 0, unsigned int a_e = 0) const inline
Read-Write Accessor (Const)
Return a const pointer to a data point in *this given a Point and tensor indices.
Parameters
a_p Point in the domain of this
a_c (Optional) First tensor index. Defaults to 0.
a_d (Optional) Second tensor index. Defaults to 0.
a_e (Optional) Third tensor index. Defaults to 0.
References Proto::BoxData< T, C, D, E >::index(), and Proto::BoxData< T, C, D, E >::m_rawPtr.
template<typename T, unsigned int C, unsigned char D, unsigned char E> const T* Proto::BoxData< T, C, D, E >::data () const inline
Return a const pointer to a data point in *this . a shortcut overload for no offsetting. ie. return rawPtr
References Proto::BoxData< T, C, D, E >::m_rawPtr.
template<typename T, unsigned int C, unsigned char D, unsigned char E> T* Proto::BoxData< T, C, D, E >::data (const Point & a_p, unsigned int a_c = 0, unsigned int a_d = 0, unsigned int a_e = 0) inline
Read-Write Accessor (Non-Const)
Return a pointer to a data point in *this given a Point and tensor indices.
Parameters
a_p Point in the domain of this
a_c (Optional) First tensor index. Defaults to 0.
a_d (Optional) Second tensor index. Defaults to 0.
a_e (Optional) Third tensor index. Defaults to 0.
References Proto::BoxData< T, C, D, E >::index(), and Proto::BoxData< T, C, D, E >::m_rawPtr.
template<typename T, unsigned int C, unsigned char D, unsigned char E> T* Proto::BoxData< T, C, D, E >::dataPtr (unsigned int a_c = 0, unsigned int a_d = 0, unsigned int a_e = 0) inline
References Proto::BoxData< T, C, D, E >::index(), Proto::Box::low(), Proto::BoxData< T, C, D, E >::m_box, and Proto::BoxData< T, C, D, E >::m_rawPtr.
Referenced by Proto::BoxData< T, C, D, E >::define().
template<typename T, unsigned int C, unsigned char D, unsigned char E> const T* Proto::BoxData< T, C, D, E >::dataPtr (unsigned int a_c = 0, unsigned int a_d = 0, unsigned int a_e = 0) const inline
References Proto::BoxData< T, C, D, E >::index(), Proto::Box::low(), Proto::BoxData< T, C, D, E >::m_box, and Proto::BoxData< T, C, D, E >::m_rawPtr.
template<typename T, unsigned int C, unsigned char D, unsigned char E> T* Proto::BoxData< T, C, D, E >::data () inline
Return a const pointer to a data point in *this . a shortcut overload for no offsetting. ie. return rawPtr
References Proto::BoxData< T, C, D, E >::m_rawPtr.
template<typename T, unsigned int C, unsigned char D, unsigned char E> shared_ptr<T> Proto::BoxData< T, C, D, E >::getData () const inline
Access Shared Pointer.
Used internally. Not recommended for public use.
< Data array
References Proto::BoxData< T, C, D, E >::m_data.
Referenced by Proto::BoxData< T, C, D, E >::define().
template<typename T, unsigned int C, unsigned char D, unsigned char E> CUDA_DECORATION size_t Proto::BoxData< T, C, D, E >::index (const Point a_pt, unsigned int a_c = 0, unsigned int a_d = 0, unsigned int a_e = 0) const inline
Compute Index.
Computes the index in [0,this->size()) associated with a given Point and components
Parameters
a_pt A Point in the domain of *this
a_c Value of first tensor index
a_d Value of second tensor index
a_e Value of third tensor index
Referenced by Proto::BoxData< T, C, D, E >::data(), Proto::BoxData< T, C, D, E >::dataPtr(), and Proto::BoxData< T, C, D, E >::var().
template<typename T, unsigned int C, unsigned char D, unsigned char E> Box Proto::BoxData< T, C, D, E >::box () const inline
Return's the domain Box of *this . Includes ghost cells if it was built it that way.
References Proto::BoxData< T, C, D, E >::m_box.
Referenced by Proto::BoxData< T, C, D, E >::define(), and Proto::Stencil< double >::operator()().
template<typename T, unsigned int C, unsigned char D, unsigned char E> std::size_t Proto::BoxData< T, C, D, E >::size () const inline
Returns the number of data points in *this . Return value is equal to m_box.size()*C*D*E
References Proto::BoxData< T, C, D, E >::m_box, and Proto::Box::size().
template<typename T, unsigned int C, unsigned char D, unsigned char E> bool Proto::BoxData< T, C, D, E >::defined () const inline
Defined Query.
Returns true if this is defined (e.g., it has memory allocated to it). This will return false for default constructed objects and true otherwise
References Proto::BoxData< T, C, D, E >::m_data.
template<class T , unsigned int C, unsigned char D, unsigned char E> Var< T, C, D, E > Proto::BoxData< T, C, D, E >::var (const Point & a_pt) inline
Create Pointwise Access Variable (Non-Const)
Not for public use
template<class T , unsigned int C, unsigned char D, unsigned char E> Var< T, C, D, E > Proto::BoxData< T, C, D, E >::var (const Point & a_pt) const inline
Create Pointwise Access Variable (Const)
Not for public use
References Proto::Box::contains(), Proto::BoxData< T, C, D, E >::index(), Proto::BoxData< T, C, D, E >::m_box, Proto::BoxData< T, C, D, E >::m_rawPtr, and PROTO_ASSERT.
template<class T , unsigned int C, unsigned char D, unsigned char E> BoxData< T, C, D, E > & Proto::BoxData< T, C, D, E >::operator+= (const BoxData< T, C, D, E > & a_rhs)
Pointwise Addition on Intersection.
Not recommended for performance unless necessary. Try to fuse arithmetic operations into forall or Stencil operations if possible.
Parameters
a_rhs Another BoxData
template<class T , unsigned int C, unsigned char D, unsigned char E> BoxData< T, C, D, E > & Proto::BoxData< T, C, D, E >::operator-= (const BoxData< T, C, D, E > & a_rhs)
Pointwise Subtraction on Intersection.
Not recommended for performance unless necessary. Try to fuse arithmetic operations into forall or Stencil operations if possible.
Parameters
a_rhs Another BoxData
References Proto::Box::contains(), Proto::Box::index(), Proto::BoxData< T, C, D, E >::m_box, PROTO_ASSERT, and Proto::Box::size().
template<class T , unsigned int C, unsigned char D, unsigned char E> BoxData< T, C, D, E > & Proto::BoxData< T, C, D, E >::operator*= (const BoxData< T, C, D, E > & a_rhs)
Pointwise Multiplication on Intersection.
Not recommended for performance unless necessary. Try to fuse arithmetic operations into forall or Stencil operations if possible.
Parameters
a_rhs Another BoxData
template<class T , unsigned int C, unsigned char D, unsigned char E> BoxData< T, C, D, E > & Proto::BoxData< T, C, D, E >::operator/= (const BoxData< T, C, D, E > & a_rhs)
Pointwise Division on Intersection.
Not recommended for performance unless necessary. Try to fuse arithmetic operations into forall or Stencil operations if possible.
Parameters
a_rhs Another BoxData
template<class T , unsigned int C, unsigned char D, unsigned char E> BoxData< T, C, D, E > & Proto::BoxData< T, C, D, E >::operator+= (T a_scale)
Pointwise Addition by Scalar.
Not recommended for performance unless necessary. Try to fuse arithmetic operations into forall or Stencil operations if possible.
Parameters
a_scale A scalare of type T
template<class T , unsigned int C, unsigned char D, unsigned char E> BoxData< T, C, D, E > & Proto::BoxData< T, C, D, E >::operator-= (T scale)
Pointwise Subtraction by Scalar.
Not recommended for performance unless necessary. Try to fuse arithmetic operations into forall or Stencil operations if possible.
Parameters
a_scale A scalare of type T
template<class T , unsigned int C, unsigned char D, unsigned char E> BoxData< T, C, D, E > & Proto::BoxData< T, C, D, E >::operator*= (T scale)
Pointwise Multiplication by Scalar.
Not recommended for performance unless necessary. Try to fuse arithmetic operations into forall or Stencil operations if possible.
Parameters
a_scale A scalare of type T
template<class T , unsigned int C, unsigned char D, unsigned char E> BoxData< T, C, D, E > & Proto::BoxData< T, C, D, E >::operator/= (T scale)
Pointwise Division by Scalar.
Not recommended for performance unless necessary. Try to fuse arithmetic operations into forall or Stencil operations if possible.
Parameters
a_scale A scalare of type T
template<class T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::setVal (const T & a_val)
Initialize All Values.
Avoid calling this function as much as possible in performance critical code
Parameters
a_val A constant value.
template<class T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::setVal (const T & a_val, const Box & a_box)
Set All Values in Box.
Avoid calling this function as much as possible in performance critical code
Parameters
a_val A constant value.
a_box Domain to set to a_val
template<class T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::setVal (const T & a_val, const Box & a_box, int a_c, int a_d = 0, int a_e = 0)
Set All Values of Component in Box.
Avoid calling this function as much as possible in performance critical code
Parameters
a_val A constant value.
a_box Domain to set to a_val
a_c First index of component to set to a_val.
a_d Second index of component to set to a_val.
a_e Third index of component to set to a_val.
template<class T , unsigned int C, unsigned char D, unsigned char E> T Proto::BoxData< T, C, D, E >::absMax () const
Absolute Maximum Value (Global)
Maximum Absolute Value (Global)
Returns the maximum absolute value over the entire data set
template<class T , unsigned int C, unsigned char D, unsigned char E> T Proto::BoxData< T, C, D, E >::absMax (int a_c, int a_d = 0, int a_e = 0) const
Absolute Maximum Value (Componentwise)
Maximum Absolute Value (Componentwise)
Returns the maximum absolute value of a given component
Parameters
a_c First tensor index.
a_d Second tensor index.
a_e Third tensor index.
template<class T , unsigned int C, unsigned char D, unsigned char E> T Proto::BoxData< T, C, D, E >::min () const
Minimum Value (Global)
Returns the minimum value over the entire data set
template<class T , unsigned int C, unsigned char D, unsigned char E> T Proto::BoxData< T, C, D, E >::min (int a_c, int a_d = 0, int a_e = 0) const
Minimum Value (Componentwise)
Returns the minimum value of a given component
Parameters
a_c First tensor index.
a_d Second tensor index.
a_e Third tensor index.
template<class T , unsigned int C, unsigned char D, unsigned char E> T Proto::BoxData< T, C, D, E >::max () const
Maximum Value (Global)
Returns the maximum value over the entire data set
template<class T , unsigned int C, unsigned char D, unsigned char E> T Proto::BoxData< T, C, D, E >::max (int a_c, int a_d = 0, int a_e = 0) const
Maximum Value (Componentwise)
Returns the maximum value of a given component
Parameters
a_c First tensor index.
a_d Second tensor index.
a_e Third tensor index.
template<class T , unsigned int C, unsigned char D, unsigned char E> T Proto::BoxData< T, C, D, E >::sum () const
Sum.
return the sum of the values (useful for projections)
template<class T , unsigned int C, unsigned char D, unsigned char E> T Proto::BoxData< T, C, D, E >::sum (int a_c, int a_d = 0, int a_e = 0) const
sum (Componentwise)
Return the sum of a particular component
Parameters
a_c First tensor index.
a_d Second tensor index.
a_e Third tensor index.
template<typename T, unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::shift (const Point a_pt) inline
Shift Domain.
Shifts the domain Box of this, moving all data along with it. e.g. data associated with Point p will now be associated with Point p + a_pt.
Parameters
a_pt A Point interpreted as a shift vector.
References Proto::BoxData< T, C, D, E >::m_box, and Proto::Box::shift().
template<class T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::linearOut (void * a_buf, const Box & a_box, CInterval a_comps) const
Buffer Write.
Write a subset of data from *this into a C-array buffer.
Example Usage:
Parameters
a_buf Destination buffer
a_box Domain to write from
a_comps Components to write from
template<typename T, unsigned int C, unsigned char D, unsigned char E> template<unsigned int ncomp> void Proto::BoxData< T, C, D, E >::define (BoxData< T, ncomp > & a_input, unsigned int & a_comp) inline
References Proto::BoxData< T, C, D, E >::box(), Proto::BoxData< T, C, D, E >::dataPtr(), Proto::BoxData< T, C, D, E >::getData(), Proto::BoxData< T, C, D, E >::m_box, Proto::BoxData< T, C, D, E >::m_data, and Proto::BoxData< T, C, D, E >::m_rawPtr.
template<class T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::linearIn (void * a_buf, const Box & a_box, CInterval a_comps)
Buffer Read.
Read data into *this from a C-array buffer populated by BoxData<T,C,D,E>::linearOut(...). The Box and components may be shifted with respect to those used for the read operation. (The number of component indices along each axis and the shape and size of the Box must be the same). See the example below.
Example Usage:
Parameters
a_buf Source buffer
a_box Domain to read from
a_comps Components to read from
template<typename T, unsigned int C, unsigned char D, unsigned char E> bool Proto::BoxData< T, C, D, E >::contains (CInterval a_interval) const inline
Contains CInterval.
Checks if an CInterval object is a subset of the component space of *this. This function is mostly used internally, but it can be useful for checking inputs to CopyTo and the slicing functions
References Proto::CInterval::high().
template<typename T, unsigned int C, unsigned char D, unsigned char E> template<unsigned int CC, unsigned char DD, unsigned char EE> bool Proto::BoxData< T, C, D, E >::isAlias (const BoxData< T, CC, DD, EE > & a_src) const inline
Check Aliasing.
Returns true if *this and a_src are aliased to the same data buffer. This function also returns true if one array is a slice of another.
References Proto::BoxData< T, C, D, E >::m_data.
template<typename T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::print () const
Print.
Default Print method. Outputs Domain Box and extrema of *this
template<typename T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::printData (int a_prec = 2) const
Print Data.
Pretty prints all of the data in *this. Prettiness may vary depending on the domain size. Generally looks best with DIM = 2 and Box edge lengths less than ~16. This function is purely for debugging purposes and should not be used in performance code.
Parameters
a_prec (Optional) Desired precision for fixed decimal output. Defaults to 2.
template<typename T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::printData (const Box & a_box, int a_prec = 2) const
Print Data in Box.
Pretty prints the data in *this within a given Box for all components. Input Boxes of size 16^DIM or smaller are recommended to maintain prettiness. This function is purely for debugging purposes and should not be used in performance code.
Parameters
a_box Desired subset for printing
a_prec (Optional) Desired precision for fixed decimal output. Defaults to 2.
template<typename T , unsigned int C, unsigned char D, unsigned char E> void Proto::BoxData< T, C, D, E >::printData (const Box & a_box, int a_c, int a_d, int a_e, int a_prec = 2) const
Print Component Data in Box.
Pretty prints the data in *this within a given Box for a single component. Input Boxes of size 16^DIM or smaller are recommended to maintain prettiness. This function is purely for debugging purposes and should not be used in performance code.
Parameters
a_box Desired subset for printing
a_c First tensor index. Defaults to 0.
a_d Second tensor index. Defaults to 0.
a_e Third tensor index. Defaults to 0.
a_prec (Optional) Desired precision for fixed decimal output. Defaults to 2
Friends And Related Function Documentation
template<typename T, unsigned int C, unsigned char D, unsigned char E> template<class TT > friend class Stencil friend
template<typename T, unsigned int C, unsigned char D, unsigned char E> template<class TT , unsigned int CC, unsigned char DD, unsigned char EE> BoxData<TT,CC,DD,EE> alias (BoxData< TT, CC, DD, EE > & a_original, const Point & a_shift) friend
template<typename T, unsigned int C, unsigned char D, unsigned char E> template<class TT , unsigned int CC, unsigned char DD, unsigned char EE> const BoxData<TT,CC,DD,EE> alias (const BoxData< TT, CC, DD, EE > & a_original, const Point & a_shift) friend
Member Data Documentation
template<typename T, unsigned int C, unsigned char D, unsigned char E> bool Proto::BoxData< T, C, D, E >::m_stackAlloc private
template<typename T, unsigned int C, unsigned char D, unsigned char E> Box Proto::BoxData< T, C, D, E >::m_box private
Box defining the domain of *this.
Referenced by Proto::BoxData< T, C, D, E >::box(), Proto::BoxData< T, C, D, E >::dataPtr(), Proto::BoxData< T, C, D, E >::define(), Proto::BoxData< T, C, D, E >::operator-=(), Proto::BoxData< T, C, D, E >::shift(), Proto::BoxData< T, C, D, E >::size(), and Proto::BoxData< T, C, D, E >::var().
template<typename T, unsigned int C, unsigned char D, unsigned char E> ::std::shared_ptr<T> Proto::BoxData< T, C, D, E >::m_data private
Data array.
Referenced by Proto::BoxData< T, C, D, E >::define(), Proto::BoxData< T, C, D, E >::defined(), Proto::BoxData< T, C, D, E >::getData(), and Proto::BoxData< T, C, D, E >::isAlias().
template<typename T, unsigned int C, unsigned char D, unsigned char E> T* Proto::BoxData< T, C, D, E >::m_rawPtr private
Raw pointer to the data.
Referenced by Proto::BoxData< T, C, D, E >::data(), Proto::BoxData< T, C, D, E >::dataPtr(), Proto::BoxData< T, C, D, E >::define(), and Proto::BoxData< T, C, D, E >::var().
The documentation for this class was generated from the following file:
Proto_BoxData.H