Proto: Proto::EBBoxData< YFACE, data_t, ncomp > Class Template Reference
Proto::EBBoxData< YFACE, data_t, ncomp > Class Template Reference
#include <Proto_EBBoxData.H>
Public Member Functions
EBBoxData ()
EBBoxData (const Box &a_box, bool a_stackAlloc)
EBBoxData (const Box &a_box, const EBGraph &a_graph)
EBBoxData (const Box &a_box)
void define (const Box &a_box, const EBGraph &a_graph)
EBDataLoc indexInfo (const EBIndex< YFACE > &a_index, int a_ivar) const
Public Member Functions inherited from Proto::BaseEBBoxData< YFACE, data_t, ncomp >
BaseEBBoxData ()
BaseEBBoxData (const Box &a_box, bool a_stackAlloc)
needed for Proto::LevelData. meaningless here becasue we need the graph.
virtual ~BaseEBBoxData ()
virtual void setVal (data_t a_val)
data_t operator() (const EBIndex< cent > &a_vof, unsigned int a_c) const
will not work on device–debugging use only
const data_t * dataPtr (int a_dataType, int a_ivar) const
for AggStencil
data_t * dataPtr (int a_dataType, int a_ivar)
for AggStencil
BoxData< data_t, ncomp > & getRegData ()
needed to apply stencils
const BoxData< data_t, ncomp > & getRegData () const
needed to apply stencils
IrregData< cent, data_t, ncomp > & getIrregData ()
needed to apply stencils
const IrregData< cent, data_t,
ncomp > & getIrregData () const
needed to apply stencils
void define (const Box &a_box, const EBGraph &a_graph)
void dataInfo (data_t *&a_dataPtr, size_t &a_datasize, unsigned int a_whichfab)
for data transfers. datasize does NOT include sizeof(data_t) (to conform with boxdata::size)
Box box () const
EBGraph ebgraph () const
Additional Inherited Members
Protected Member Functions inherited from Proto::BaseEBBoxData< YFACE, data_t, ncomp >
BaseEBBoxData (const BaseEBBoxData< cent, data_t, ncomp > &a_src)
BaseEBBoxData & operator= (const BaseEBBoxData< cent, data_t, ncomp > &a_src)
Protected Attributes inherited from Proto::BaseEBBoxData< YFACE, data_t, ncomp >
EBGraph m_graph
PointSet m_irreg
BoxData< data_t, ncomp > m_regData
IrregData< cent, data_t, ncomp > m_irrData
Constructor & Destructor Documentation
template<typename data_t , unsigned int ncomp> Proto::EBBoxData< YFACE, data_t, ncomp >::EBBoxData () inline
template<typename data_t , unsigned int ncomp> Proto::EBBoxData< YFACE, data_t, ncomp >::EBBoxData (const Box & a_box, bool a_stackAlloc) inline
template<typename data_t , unsigned int ncomp> Proto::EBBoxData< YFACE, data_t, ncomp >::EBBoxData (const Box & a_box, const EBGraph & a_graph) inline
References Proto::EBBoxData< cent, data_t, ncomp >::define().
template<typename data_t , unsigned int ncomp> Proto::EBBoxData< YFACE, data_t, ncomp >::EBBoxData (const Box & a_box) inline
Member Function Documentation
template<typename data_t , unsigned int ncomp> void Proto::EBBoxData< YFACE, data_t, ncomp >::define (const Box & a_box, const EBGraph & a_graph) inline
References Proto::BaseEBBoxData< cent, data_t, ncomp >::define().
template<typename data_t , unsigned int ncomp> EBDataLoc Proto::EBBoxData< YFACE, data_t, ncomp >::indexInfo (const EBIndex< YFACE > & a_index, int a_ivar) const inline
References Proto::Point::Basis(), Proto::BoxData< T, C, D, E >::index(), Proto::EBDataLoc::m_dataID, Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irrData, Proto::BaseEBBoxData< cent, data_t, ncomp >::m_irreg, Proto::EBDataLoc::m_offset, Proto::EBIndex< cent >::m_pt, and Proto::BaseEBBoxData< cent, data_t, ncomp >::m_regData.
The documentation for this class was generated from the following file:
Proto_EBBoxData.H