Proto: Proto::EBGraph Class Reference
Proto::EBGraph Class Reference
Geometric description within a box.
#include <Proto_EBGraph.H>
Classes
struct localData
Public Types
enum TAG { AllRegular = 0, AllCovered, HasIrregular }
Public Member Functions
EBGraph ()
template<CENTERING cent>
bool isFaceRegular (const EBIndex< cent > &a_face) const
template<CENTERING cent>
bool isFaceCovered (const EBIndex< cent > &a_face) const
EBGraph (const Box &a_box, bool a_stackAlloc)
needed for Proto::LevelData. meaningless here becasue we need the graph.
vector< EBIndex< CELL > > getVoFsThatCoarsenTo (const EBIndex< CELL > &a_coarVoF) const
given vof on a coarser level, get vofs on THIS level it was coarsened from
EBGraph (const Box &a_grid)
needed for leveldata
void copy (const EBGraph &a_dsrc, const Box &a_srcBox, unsigned int a_srcComp, const Box &a_destBox, unsigned int a_destComp, unsigned int a_numcomp)
virtual ~EBGraph ()
template<CENTERING cent>
bool getAdjacentFace (EBIndex< cent > &a_adjFace, const EBIndex< cent > &a_startFace, int a_tanDir, Side::LoHiSide a_side) const
returns false if no such unique face exists (multivalued, outside of the domain, whatever)
vector< EBIndex< CELL > > getVoFs (const Point &a_iv) const
vector< EBIndex< CELL > > getAllVoFsWithinRadius (const Point &a_iv, unsigned int a_radius) const
bool isAllRegular () const
bool hasIrregular () const
bool isAllCovered () const
bool isIrregular (const Point &a_iv) const
bool isCovered (const Box &a_box) const
bool isRegular (const Box &a_box) const
bool isRegular (const Point &a_iv) const
bool isCovered (const Point &a_iv) const
bool isConnected (const EBIndex< CELL > &a_vof1, const EBIndex< CELL > &a_vof2) const
vector< EBIndex< XFACE > > getXFaces (const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd) const
vector< EBIndex< YFACE > > getYFaces (const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd) const
vector< EBIndex< CELL > > getNeighborVoFs (const EBIndex< CELL > &a_vof, const unsigned int &a_dir, const Side::LoHiSide &a_sd) const
void defineFromPrimitives (const Box &a_validBox, const HostBoxData< int > &a_regIrregCovered, const vector< IrregGraph > &a_irregGraph, const Box &a_validRegion, const Box &a_domain, bool singleValuedOnly=true)
void defineAsAllRegular (const Box &a_validBox, const Box &a_region, const Box &a_domain)
void defineAsAllCovered (const Box &a_validBox, const Box &a_region, const Box &a_domain)
const Box & getRegion () const
const Box & validBox () const
const Box & box () const
const Box & getDomain () const
bool isDefined () const
PointSet getIrregCells (const Box &a_box) const
vector< EBIndex< CELL > > getIrregVoFs (const Box &a_box) const
vector< set< EBIndex< CELL > > > getVoFSets (const Box &a_region) const
used in coarsening–get collections of connected vofs
bool hasBoundaryFaces (const EBIndex< CELL > &a_vof, int a_idir, Side::LoHiSide a_sd)
vector< EBIndex< BOUNDARY > > getCutFaces (const Point &a_pt) const
vector< EBIndex< BOUNDARY > > getCutFaces (const Box &a_box) const
get the cut faces (basically the same as above
vector< EBIndex< XFACE > > getIrregXFaces (const Box &a_box) const
get the faces where at least one vof is cut
vector< EBIndex< YFACE > > getIrregYFaces (const Box &a_box) const
template<CENTERING cent>
vector< EBIndex< cent > > refine (const EBIndex< cent > &a_ind, const EBGraph &a_finer) const
for faces
template<CENTERING cent>
EBIndex< cent > coarsen (const EBIndex< cent > &a_cent) const
vector< EBIndex< CELL > > refine (const EBIndex< CELL > &a_vof) const
void coarsenVoFs (const Box &a_validBox, EBGraph &a_fineEBGraph, const Box &a_vofRegionCoar)
void coarsenFaces (const EBGraph &a_fineEBGraph, const Box &a_faceRegionCoar)
vector< int > coarsenFaces (const EBGraph &a_fineEBGraph, const Box &a_regionCoar, const EBIndex< CELL > &a_vofCoar, const int &a_idir, const Side::LoHiSide &a_sd)
bool hasBoundaryFaces (const EBIndex< CELL > &a_vof, int a_idir, Side::LoHiSide a_sd) const
virtual std::size_t charsize (const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps) const
Chombo leveldata serialization routines.
virtual void linearIn (void *a_buf, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps)
virtual void linearOut (void *a_buf, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps) const
Static Public Member Functions
static int preAllocatable ()
Private Member Functions
void defineAsFullIrregular (const Box &a_validBox, const Box &a_region, const Box &a_domain)
void defineAsEmptyIrregular (const Box &a_validBox, const Box &a_region, const Box &a_domain)
Private Attributes
TAG m_tag
Box m_region
box over which this graph is defined
Box m_validBox
Box m_domain
computational domain at this level of refinement
bool m_isDefined
shared_ptr< localData > m_internals
Detailed Description
Geometric description within a box.
EBGraph represents the geometric information of the domain at a given refinement within the boundaries of a particular box.
Member Enumeration Documentation
enum Proto::EBGraph::TAG
The EBGraph can be all regular or all covered or contain irregular cells.
Enumerator
AllRegular
AllCovered
HasIrregular
Constructor & Destructor Documentation
Proto::EBGraph::EBGraph () inline
Makes an EBGraph whose contents are undefined.
References m_isDefined.
Proto::EBGraph::EBGraph (const Box & a_box, bool a_stackAlloc) inline
needed for Proto::LevelData. meaningless here becasue we need the graph.
Proto::EBGraph::EBGraph (const Box & a_grid) inline
needed for leveldata
References m_isDefined.
virtual Proto::EBGraph::~EBGraph () inline virtual
Member Function Documentation
template<CENTERING cent> bool Proto::EBGraph::isFaceRegular (const EBIndex< cent > & a_face) const inline
template<CENTERING cent> bool Proto::EBGraph::isFaceCovered (const EBIndex< cent > & a_face) const inline
vector<EBIndex<CELL> > Proto::EBGraph::getVoFsThatCoarsenTo (const EBIndex< CELL > & a_coarVoF) const inline
given vof on a coarser level, get vofs on THIS level it was coarsened from
This is useful when you only have the graph on the finer level but need to refine the coarser vof. Trust me, it comes up.
References Proto::Box::begin(), coarsen(), Proto::Box::end(), getVoFs(), and Proto::Box::refine().
static int Proto::EBGraph::preAllocatable () inline static
void Proto::EBGraph::copy (const EBGraph & a_dsrc, const Box & a_srcBox, unsigned int a_srcComp, const Box & a_destBox, unsigned int a_destComp, unsigned int a_numcomp) inline
template<CENTERING cent> bool Proto::EBGraph::getAdjacentFace (EBIndex< cent > & a_adjFace, const EBIndex< cent > & a_startFace, int a_tanDir, Side::LoHiSide a_side) const inline
returns false if no such unique face exists (multivalued, outside of the domain, whatever)
tandir should be shomething different from face.direction
vector< EBIndex<CELL> > Proto::EBGraph::getVoFs (const Point & a_iv) const inline
Return the VoFs in the cell.
Referenced by getAllVoFsWithinRadius(), getIrregVoFs(), getIrregXFaces(), getIrregYFaces(), and getVoFsThatCoarsenTo().
vector< EBIndex<CELL> > Proto::EBGraph::getAllVoFsWithinRadius (const Point & a_iv, unsigned int a_radius) const inline
References Proto::Box::begin(), Proto::Box::end(), getVoFs(), Proto::Box::grow(), and m_domain.
bool Proto::EBGraph::isAllRegular () const inline
Return true if every cell in the EBGraph is a regular cell.
References AllRegular, and m_tag.
bool Proto::EBGraph::hasIrregular () const inline
Return true neither all regular nor all covered
References HasIrregular, and m_tag.
Referenced by getIrregCells().
bool Proto::EBGraph::isAllCovered () const inline
Return true if every cell in the EBGraph is a covered cell.
References AllCovered, and m_tag.
bool Proto::EBGraph::isIrregular (const Point & a_iv) const inline
Return true if a_iv is an irregular cell.
Referenced by Proto::BaseEBHostData< cent, data_t, ncomp >::operator()().
bool Proto::EBGraph::isCovered (const Box & a_box) const inline
Return true if every cell in a_box is a covered cell.
bool Proto::EBGraph::isRegular (const Box & a_box) const inline
Return true if every cell in a_box is a regular cell.
bool Proto::EBGraph::isRegular (const Point & a_iv) const inline
bool Proto::EBGraph::isCovered (const Point & a_iv) const inline
bool Proto::EBGraph::isConnected (const EBIndex< CELL > & a_vof1, const EBIndex< CELL > & a_vof2) const inline
vector< EBIndex<XFACE> > Proto::EBGraph::getXFaces (const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd) const inline
Return the faces on the side and direction of the input VoF.
Referenced by getIrregXFaces(), getNeighborVoFs(), and Proto::getSideFaces().
vector< EBIndex<YFACE> > Proto::EBGraph::getYFaces (const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd) const inline
Return the faces on the side and direction of the input VoF.
Referenced by getIrregYFaces(), getNeighborVoFs(), and Proto::getSideFaces().
vector<EBIndex<CELL> > Proto::EBGraph::getNeighborVoFs (const EBIndex< CELL > & a_vof, const unsigned int & a_dir, const Side::LoHiSide & a_sd) const inline
References getXFaces(), getYFaces(), and PROTO_ASSERT.
void Proto::EBGraph::defineFromPrimitives (const Box & a_validBox, const HostBoxData< int > & a_regIrregCovered, const vector< IrregGraph > & a_irregGraph, const Box & a_validRegion, const Box & a_domain, bool singleValuedOnly = true) inline
Completely construct the graph from IrregGraphs. This makes a DENSE representation of the graph. To make sparse representations of all regular or all covered graphs, use setToAllRegular or setToAllCovered.\ irregGraph contains a complete list of irregular vofs. \ validRegion is the the region of the graph \ domain is the domain of compuation \ regIrregCovered = 1 for regular, 0 for irregular, -1 for covered. regIrregCovered must contain the valid region grown by 1. \ In chombospeak, \ regIrregCovered.box().contains(grow(validRegion, 1) & domain); \ otherwise an error will result. SingleValuedOnly signals that the geometry generator can only generate single-valued cut cells (GeometryService has this quality). Coarsening can still create multi-valued cells.
void Proto::EBGraph::defineAsAllRegular (const Box & a_validBox, const Box & a_region, const Box & a_domain) inline
Set the graph to all regular cells (sparse);
void Proto::EBGraph::defineAsAllCovered (const Box & a_validBox, const Box & a_region, const Box & a_domain) inline
Set the graph to all regular cells (sparse);
const Box& Proto::EBGraph::getRegion () const inline
References m_region.
const Box& Proto::EBGraph::validBox () const inline
References m_validBox.
const Box& Proto::EBGraph::box () const inline
References m_region.
const Box& Proto::EBGraph::getDomain () const inline
References m_domain.
bool Proto::EBGraph::isDefined () const inline
References m_isDefined.
PointSet Proto::EBGraph::getIrregCells (const Box & a_box) const inline
References hasIrregular(), m_internals, m_isDefined, and PR_assert.
Referenced by getCutFaces(), getIrregVoFs(), getIrregXFaces(), and getIrregYFaces().
vector< EBIndex<CELL> > Proto::EBGraph::getIrregVoFs (const Box & a_box) const inline
References getIrregCells(), getVoFs(), and m_domain.
vector< set<EBIndex<CELL> > > Proto::EBGraph::getVoFSets (const Box & a_region) const inline
used in coarsening–get collections of connected vofs
bool Proto::EBGraph::hasBoundaryFaces (const EBIndex< CELL > & a_vof, int a_idir, Side::LoHiSide a_sd) inline
vector< EBIndex<BOUNDARY> > Proto::EBGraph::getCutFaces (const Point & a_pt) const inline
Referenced by getCutFaces().
vector< EBIndex<BOUNDARY> > Proto::EBGraph::getCutFaces (const Box & a_box) const inline
get the cut faces (basically the same as above
References getCutFaces(), getIrregCells(), and m_domain.
vector<EBIndex<XFACE> > Proto::EBGraph::getIrregXFaces (const Box & a_box) const inline
get the faces where at least one vof is cut
References getIrregCells(), getVoFs(), getXFaces(), m_domain, and Proto::SideIterator::ok().
Referenced by Proto::getIrregFaces().
vector<EBIndex<YFACE> > Proto::EBGraph::getIrregYFaces (const Box & a_box) const inline
References getIrregCells(), getVoFs(), getYFaces(), and Proto::SideIterator::ok().
Referenced by Proto::getIrregFaces().
template<CENTERING cent> vector< EBIndex<cent> > Proto::EBGraph::refine (const EBIndex< cent > & a_ind, const EBGraph & a_finer) const inline
for faces
template<CENTERING cent> EBIndex<cent> Proto::EBGraph::coarsen (const EBIndex< cent > & a_cent) const inline
Referenced by getVoFsThatCoarsenTo().
vector< EBIndex<CELL> > Proto::EBGraph::refine (const EBIndex< CELL > & a_vof) const inline
void Proto::EBGraph::coarsenVoFs (const Box & a_validBox, EBGraph & a_fineEBGraph, const Box & a_vofRegionCoar) inline
void Proto::EBGraph::coarsenFaces (const EBGraph & a_fineEBGraph, const Box & a_faceRegionCoar) inline
vector<int> Proto::EBGraph::coarsenFaces (const EBGraph & a_fineEBGraph, const Box & a_regionCoar, const EBIndex< CELL > & a_vofCoar, const int & a_idir, const Side::LoHiSide & a_sd) inline
bool Proto::EBGraph::hasBoundaryFaces (const EBIndex< CELL > & a_vof, int a_idir, Side::LoHiSide a_sd) const inline
virtual std::size_t Proto::EBGraph::charsize (const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps) const inline virtual
Chombo leveldata serialization routines.
virtual void Proto::EBGraph::linearIn (void * a_buf, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps) inline virtual
virtual void Proto::EBGraph::linearOut (void * a_buf, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps) const inline virtual
void Proto::EBGraph::defineAsFullIrregular (const Box & a_validBox, const Box & a_region, const Box & a_domain) inline private
void Proto::EBGraph::defineAsEmptyIrregular (const Box & a_validBox, const Box & a_region, const Box & a_domain) inline private
Member Data Documentation
TAG Proto::EBGraph::m_tag private
If this is allregular or allcovered, the HostBoxData below is undefined.
Referenced by hasIrregular(), isAllCovered(), and isAllRegular().
Box Proto::EBGraph::m_region private
box over which this graph is defined
Referenced by box(), and getRegion().
Box Proto::EBGraph::m_validBox private
Referenced by validBox().
Box Proto::EBGraph::m_domain private
computational domain at this level of refinement
Referenced by getAllVoFsWithinRadius(), getCutFaces(), getDomain(), getIrregVoFs(), and getIrregXFaces().
bool Proto::EBGraph::m_isDefined private
Referenced by EBGraph(), getIrregCells(), and isDefined().
shared_ptr<localData> Proto::EBGraph::m_internals private
Referenced by getIrregCells().
The documentation for this class was generated from the following file:
Proto_EBGraph.H