Proto: Proto::TraceTimer Class Reference
Proto::TraceTimer Class Reference
#include <Proto_Timer.H>
Public Member Functions
virtual ~TraceTimer ()
TraceTimer ()
void start (char *mutex)
unsigned long long int stop (char *mutex)
void report (bool a_closeAfter=false)
void reset ()
void leafStart ()
void leafStop ()
unsigned long long int time () const
int rank () const
long long int count () const
void prune ()
bool isPruned () const
void setTimerFileName (string a_filename)
need to set the filename so it is not /dev/null
TraceTimer * getTimer (const char *name)
const std::vector< TraceTimer * > & children () const
void PruneTimersParentChildPercent (double percent)
void sampleMemUsage ()
void addFlops (long long int flops)
Static Public Member Functions
static std::vector< TraceTimer * > * getRootTimerPtr ()
static std::vector< TraceTimer * > * getCurrentTimerPtr ()
static void staticReport ()
static void staticReset ()
static void staticPruneTimersParentChildPercent (double percent)
static void staticSetTimerFileName (string a_filename)
static int getTID ()
static TraceTimer * staticGetTimer (const char *name)
Public Attributes
const char * m_name
int m_rank
int tid = 0
int m_thread_id
long long int m_flops
long long int m_count
Private Member Functions
TraceTimer (const char *a_name, TraceTimer *parent, int thread_id)
void reportTree (FILE *out, const TraceTimer &node, int depth)
const TraceTimer * activeChild () const
void macroTest ()
void macroTest2 ()
void currentize () const
void reportFullTree (FILE *out, const TraceTimer &timer, unsigned long long int totalTime, int depth, double secondspertick)
void reportOneTree (FILE *out, const TraceTimer &timer, double secondspertick)
void reset (TraceTimer &timer)
void PruneTimersParentChildPercent (double threshold, TraceTimer *parent)
void sumFlops (TraceTimer &timer)
Private Attributes
string m_filename
bool m_pruned
TraceTimer * m_parent
std::vector< TraceTimer * > m_children
unsigned long long int m_accumulated_WCtime
unsigned long long int m_last_WCtime_stamp
double zeroTime = 0
unsigned long long int zeroTicks = 0
int m_depth
Constructor & Destructor Documentation
virtual Proto::TraceTimer::~TraceTimer () inline virtual
References m_children.
Proto::TraceTimer::TraceTimer () inline
References m_filename.
Referenced by getRootTimerPtr().
Proto::TraceTimer::TraceTimer (const char * a_name, TraceTimer * parent, int thread_id) inline private
References m_accumulated_WCtime, m_count, m_flops, m_last_WCtime_stamp, m_name, m_parent, m_pruned, and m_thread_id.
Member Function Documentation
void Proto::TraceTimer::start (char * mutex) inline
Referenced by Proto::AutoStart::AutoStart(), and getRootTimerPtr().
unsigned long long int Proto::TraceTimer::stop (char * mutex) inline
Referenced by Proto::AutoStart::~AutoStart().
void Proto::TraceTimer::report (bool a_closeAfter = false) inline
void Proto::TraceTimer::reset () inline
void Proto::TraceTimer::leafStart () inline
References m_count, m_last_WCtime_stamp, and m_pruned.
Referenced by Proto::AutoStartLeaf::AutoStartLeaf().
void Proto::TraceTimer::leafStop () inline
References m_accumulated_WCtime, m_last_WCtime_stamp, and m_pruned.
Referenced by Proto::AutoStartLeaf::~AutoStartLeaf().
unsigned long long int Proto::TraceTimer::time () const inline
References m_accumulated_WCtime.
int Proto::TraceTimer::rank () const inline
References m_rank.
long long int Proto::TraceTimer::count () const inline
References m_count.
void Proto::TraceTimer::prune ()
bool Proto::TraceTimer::isPruned () const inline
References m_pruned.
void Proto::TraceTimer::setTimerFileName (string a_filename) inline
need to set the filename so it is not /dev/null
References getRootTimerPtr().
TraceTimer* Proto::TraceTimer::getTimer (const char * name) inline
Referenced by staticGetTimer().
const std::vector<TraceTimer*>& Proto::TraceTimer::children () const inline
void Proto::TraceTimer::PruneTimersParentChildPercent (double percent) inline
void Proto::TraceTimer::sampleMemUsage () inline
void Proto::TraceTimer::addFlops (long long int flops) inline
References m_flops.
static std::vector<TraceTimer*>* Proto::TraceTimer::getRootTimerPtr () inline static
References getCurrentTimerPtr(), m_thread_id, start(), tid, Proto::TimerGetTimeStampWC(), TraceTimer(), zeroTicks, and zeroTime.
Referenced by getTID(), setTimerFileName(), staticGetTimer(), staticPruneTimersParentChildPercent(), staticReport(), staticReset(), and staticSetTimerFileName().
static std::vector<TraceTimer*>* Proto::TraceTimer::getCurrentTimerPtr () inline static
Referenced by getRootTimerPtr().
static void Proto::TraceTimer::staticReport () inline static
References getRootTimerPtr().
static void Proto::TraceTimer::staticReset () inline static
References getRootTimerPtr().
static void Proto::TraceTimer::staticPruneTimersParentChildPercent (double percent) inline static
References getRootTimerPtr().
static void Proto::TraceTimer::staticSetTimerFileName (string a_filename) inline static
References getRootTimerPtr().
static int Proto::TraceTimer::getTID () inline static
References getRootTimerPtr().
static TraceTimer* Proto::TraceTimer::staticGetTimer (const char * name) inline static
References getRootTimerPtr(), and getTimer().
void Proto::TraceTimer::reportTree (FILE * out, const TraceTimer & node, int depth) private
const TraceTimer* Proto::TraceTimer::activeChild () const private
void Proto::TraceTimer::macroTest () inline private
void Proto::TraceTimer::macroTest2 () inline private
void Proto::TraceTimer::currentize () const inline private
void Proto::TraceTimer::reportFullTree (FILE * out, const TraceTimer & timer, unsigned long long int totalTime, int depth, double secondspertick) inline private
void Proto::TraceTimer::reportOneTree (FILE * out, const TraceTimer & timer, double secondspertick) inline private
void Proto::TraceTimer::reset (TraceTimer & timer) inline private
void Proto::TraceTimer::PruneTimersParentChildPercent (double threshold, TraceTimer * parent) inline private
void Proto::TraceTimer::sumFlops (TraceTimer & timer) inline private
Member Data Documentation
const char* Proto::TraceTimer::m_name
Referenced by TraceTimer().
int Proto::TraceTimer::m_rank mutable
Referenced by rank().
int Proto::TraceTimer::tid = 0
Referenced by getRootTimerPtr().
int Proto::TraceTimer::m_thread_id
Referenced by getRootTimerPtr(), and TraceTimer().
long long int Proto::TraceTimer::m_flops
Referenced by addFlops(), and TraceTimer().
long long int Proto::TraceTimer::m_count
Referenced by count(), leafStart(), and TraceTimer().
string Proto::TraceTimer::m_filename private
Referenced by TraceTimer().
bool Proto::TraceTimer::m_pruned private
Referenced by isPruned(), leafStart(), leafStop(), and TraceTimer().
TraceTimer* Proto::TraceTimer::m_parent private
Referenced by TraceTimer().
std::vector<TraceTimer*> Proto::TraceTimer::m_children private
Referenced by ~TraceTimer().
unsigned long long int Proto::TraceTimer::m_accumulated_WCtime private
Referenced by leafStop(), time(), and TraceTimer().
unsigned long long int Proto::TraceTimer::m_last_WCtime_stamp private
Referenced by leafStart(), leafStop(), and TraceTimer().
double Proto::TraceTimer::zeroTime = 0 private
Referenced by getRootTimerPtr().
unsigned long long int Proto::TraceTimer::zeroTicks = 0 private
Referenced by getRootTimerPtr().
int Proto::TraceTimer::m_depth private
The documentation for this class was generated from the following file:
Proto_Timer.H