Proto: Proto::SimpleEllipsoidIF Class Reference
Proto::SimpleEllipsoidIF Class Reference
Ellipsoid.
#include <Proto_SimpleImplicitFunctions.H>
Public Member Functions
SimpleEllipsoidIF (const RealVect &a_ABE, const RealVect &a_X0, const double &a_R, const bool &a_inside)
bool sameQuadrant (vector< RealVect > a_cornerlocs)
virtual bool entireBoxRegular (const Box &a_box, const RealVect &a_origin, const double &a_dx)
return true if the box is entirely in the fluid
virtual bool entireBoxCovered (const Box &a_box, const RealVect &a_origin, const double &a_dx)
return true if the entire box is covered by the ellipsoid
virtual ~SimpleEllipsoidIF ()
Destructor.
double value (const IndexTM< double, DIM > &a_point) const
virtual double value (const IndexTM< int, DIM > &a_partialDerivative, const IndexTM< double, DIM > &a_point) const
virtual BaseIF * newImplicitFunction () const
factory method
Public Member Functions inherited from Proto::SimpleGeometry
IndexTM< double, DIM > getIndexTM (const RealVect &a_rv)
vector< RealVect > getCornerLocations (const Box &a_box, const RealVect &a_origin, const double &a_dx)
Public Member Functions inherited from Proto::BaseIF
BaseIF ()
Default constructor.
virtual ~BaseIF ()
Default destructor.
Protected Attributes
RealVect m_ABE
RealVect m_X0
double m_R
bool m_inside
RealVect m_A2
Private Member Functions
SimpleEllipsoidIF ()
Detailed Description
Ellipsoid.
((x-xo)/A)^2 + ((y-y0)/B)^2 + ((z-z0)/C)^2 - r^2 = f(x,y,z)
Constructor & Destructor Documentation
Proto::SimpleEllipsoidIF::SimpleEllipsoidIF (const RealVect & a_ABE, const RealVect & a_X0, const double & a_R, const bool & a_inside) inline
References m_A2, m_ABE, m_inside, m_R, m_X0, and PR_assert.
virtual Proto::SimpleEllipsoidIF::~SimpleEllipsoidIF () inline virtual
Destructor.
Proto::SimpleEllipsoidIF::SimpleEllipsoidIF () private
Referenced by newImplicitFunction().
Member Function Documentation
bool Proto::SimpleEllipsoidIF::sameQuadrant (vector< RealVect > a_cornerlocs) inline
References m_X0.
Referenced by entireBoxCovered(), and entireBoxRegular().
virtual bool Proto::SimpleEllipsoidIF::entireBoxRegular (const Box & a_box, const RealVect & a_origin, const double & a_dx) inline virtual
return true if the box is entirely in the fluid
Reimplemented from Proto::BaseIF.
References Proto::SimpleGeometry::getCornerLocations(), Proto::SimpleGeometry::getIndexTM(), sameQuadrant(), and value().
virtual bool Proto::SimpleEllipsoidIF::entireBoxCovered (const Box & a_box, const RealVect & a_origin, const double & a_dx) inline virtual
return true if the entire box is covered by the ellipsoid
Reimplemented from Proto::BaseIF.
References Proto::SimpleGeometry::getCornerLocations(), Proto::SimpleGeometry::getIndexTM(), sameQuadrant(), and value().
double Proto::SimpleEllipsoidIF::value (const IndexTM< double, DIM > & a_point) const inline
References m_A2, m_inside, m_R, and m_X0.
Referenced by entireBoxCovered(), entireBoxRegular(), and value().
virtual double Proto::SimpleEllipsoidIF::value (const IndexTM< int, DIM > & a_partialDerivative, const IndexTM< double, DIM > & a_point) const inline virtual
Return the value of the function at a_point. When delineating a domain, the level set value=0 represents the boundary and value<0 is inside the fluid.
Implements Proto::BaseIF.
References m_A2, m_inside, m_X0, and value().
virtual BaseIF* Proto::SimpleEllipsoidIF::newImplicitFunction () const inline virtual
factory method
Return a newly allocated derived class. The responsibility for deleting the memory is left to the calling function.
Implements Proto::BaseIF.
References m_ABE, m_inside, m_R, m_X0, and SimpleEllipsoidIF().
Member Data Documentation
RealVect Proto::SimpleEllipsoidIF::m_ABE protected
Referenced by newImplicitFunction(), and SimpleEllipsoidIF().
RealVect Proto::SimpleEllipsoidIF::m_X0 protected
Referenced by newImplicitFunction(), sameQuadrant(), SimpleEllipsoidIF(), and value().
double Proto::SimpleEllipsoidIF::m_R protected
Referenced by newImplicitFunction(), SimpleEllipsoidIF(), and value().
bool Proto::SimpleEllipsoidIF::m_inside protected
Referenced by newImplicitFunction(), SimpleEllipsoidIF(), and value().
RealVect Proto::SimpleEllipsoidIF::m_A2 protected
Referenced by SimpleEllipsoidIF(), and value().
The documentation for this class was generated from the following file:
Proto_SimpleImplicitFunctions.H