Proto: Proto::SideIterator Class Reference
Proto::SideIterator Class Reference
Iterator for low and high side.
#include <Proto_LoHiSide.H>
Public Member Functions
SideIterator ()
~SideIterator ()
Modification functions
void begin ()
void reset ()
void next ()
void operator++ ()
Access functions
int m_current
Side::LoHiSide operator() () const
bool ok () const
Detailed Description
Iterator for low and high side.
SideIterator iterates over the values Side::Lo and Side::Hi. There are no adjustable parameters whatsoever.
Constructor & Destructor Documentation
Proto::SideIterator::SideIterator () inline
Default, and only, constructor.
References m_current, and reset().
Proto::SideIterator::~SideIterator () inline
Default destructor.
Member Function Documentation
void Proto::SideIterator::begin () inline
Set the iterator to the first side.
References m_current.
Referenced by reset().
void Proto::SideIterator::reset () inline
Set the iterator to the first side.
References begin().
Referenced by SideIterator().
void Proto::SideIterator::next () inline
Advance the iterator to the next face.
References m_current.
void Proto::SideIterator::operator++ () inline
Advance the iterator to the next face.
References m_current.
Side::LoHiSide Proto::SideIterator::operator() () const inline
Returns the value of the side for the current iteration.
References Proto::Side::Hi, Proto::Side::Invalid, Proto::Side::Lo, and m_current.
bool Proto::SideIterator::ok () const inline
Returns true if there is a next side, false if not.
References m_current, and Proto::Side::NUMSIDES.
Referenced by Proto::EBGraph::getIrregXFaces(), and Proto::EBGraph::getIrregYFaces().
Member Data Documentation
int Proto::SideIterator::m_current private
Referenced by begin(), next(), ok(), operator()(), operator++(), and SideIterator().
The documentation for this class was generated from the following file:
Proto_LoHiSide.H