Proto: Proto::Box Class Reference
Proto::Box Class Reference
An interval in DIM dimensional space.
#include <Proto_Box.H>
Public Types
typedef BoxIterator iterator
Public Member Functions
Constructors
Box ()
Default Constructor.
Box (const Point &a_low, const Point &a_high)
2 Point Constructor
Box (const int *a_lo, const int *a_hi)
Primitive Constructor.
void define (const int *a_lo, const int *a_hi)
Define.
Box (const Point &a_pt)
1 Point (Origin) Constructor
Box (const Box &a_box)
Copy Constructor.
Accessors And Queries
Point low () const
Access Low Corner.
Point high () const
Access High Corner.
CUDA_DECORATION std::size_t size (unsigned char a_dim) const
Edge Size.
CUDA_DECORATION std::size_t size () const
Volumetric Size.
bool contains (const Point &a_pt) const
Contains Point Query.
bool contains (const Box &a_rhs) const
Contains Box Query.
bool onBoundary (const Point &a_p) const
Point on Boundry Query.
bool empty () const
Empty Query.
CUDA_DECORATION unsigned int index (const Point &a_pt) const
Point to Linear Index.
CUDA_DECORATION Point operator[] (unsigned int a_index) const
Access Point by Index.
Operators
Box operator& (const Box &a_rightBox) const
Intersection Operator.
void operator&= (const Box &a_rightBox)
Box operator& (Point a_pt) const
Add Point Operator.
bool operator== (const Box &a_rhsBox) const
Equality Operator.
bool operator!= (const Box &a_rhsBox) const
Inequality Operator.
Point operator% (const Point &a_pt) const
Modulus Operator.
Transformations
Box shift (int a_direction, int a_offset) const
Shift Transformation.
Box shift (const Point &a_pt) const
Point Shift Transformation.
Box grow (const Point &a_pt) const
Anisotropic Grow Operation.
Box grow (int idir, int igrow) const
grows both low and high
Box growHi (int idir, int igrow) const
grows only high side
Box growLo (int idir, int igrow) const
grows only low side
Box grow (int a_numpoints) const
Isotropic Grow Operation.
Box coarsen (const Point &a_pt) const
Anisotropic Coarsen Operation.
Box coarsen (unsigned int a_ratio) const
Isotropic Coarsen Operation.
bool coarsenable (const int &a_ratio) const
Coarsenable Query.
Box taperCoarsen (const Point &a_ref)
Box refine (const Point &a_pt) const
Anisotropic Refine Operation.
Box refine (unsigned int a_ratio) const
Isotropic Refine Operation.
Box flatten (const int a_dir, bool a_upper=false) const
Flatten.
Box adjCellLo (int a_idir, int a_length) const
Box adjCellHi (int a_idir, int a_length) const
Box edge (const Point &a_dir) const
Edge.
Box extrude (int a_dir, int a_dist=1, bool a_upper=true) const
Extrude.
Utility
BoxIterator begin () const
Iterator Begin.
BoxIterator end () const
Iterator End.
BoxIterator rbegin () const
Iterator Reverse Begin.
BoxIterator rend () const
Iterator Reverse End.
Point mod (const Point &a_pt) const
Point Modulus Operation.
void print () const
Print.
Static Public Member Functions
static CUDA_DECORATION unsigned int sindex (Point a_pt, Point a_low, Point a_high)
for stencil internals
static CUDA_DECORATION int soffset (const Point &a_pt, const Point &a_low, const Point &a_high)
Static Functions
static Box Cube (int a_size)
Private Member Functions
void recomputeSize ()
Used to reevaluate the size of the box when it is changed.
Private Attributes
Point m_low
Point object containing the lower bounds of the Box.
Point m_high
Point object containing the upper bounds of the Box.
int m_size
"Volume" of the box.
Detailed Description
An interval in DIM dimensional space.
A Box is a region in specified by two corner Point objects, high and low INCLUSIVELY.
Equivalently, a Box is a collection of linear intervals in .
Boxes are written using the notation [low, high] .
Member Typedef Documentation
typedef BoxIterator Proto::Box::iterator
Constructor & Destructor Documentation
Proto::Box::Box () inline
Default Constructor.
Builds the empty Box [(-1,-1,...,-1), (0,0,...,0)]
Referenced by adjCellHi(), adjCellLo(), define(), and taperCoarsen().
Proto::Box::Box (const Point & a_low, const Point & a_high) inline
2 Point Constructor
Builds the non-trivial Bx [low, high]
Parameters
a_low low corner
a_high high corner
Proto::Box::Box (const int * a_lo, const int * a_hi) inline
Primitive Constructor.
Used for building a Bx on platforms where plain-old-data is more convenient
Parameters
a_lo C-Array representing this.low()
a_hi C-Array representing this.high()
Proto::Box::Box (const Point & a_pt) inline
1 Point (Origin) Constructor
Builds the non-trivial Box [(0,...,0), a_pt]
Parameters
a_pt high corner
Proto::Box::Box (const Box & a_box) inline
Copy Constructor.
Member Function Documentation
void Proto::Box::define (const int * a_lo, const int * a_hi) inline
Define.
Weak construct this Bx if necessary
Parameters
a_lo C-Array representing this.low()
a_hi C-Array representing this.high()
References Box().
Referenced by Cube().
Box Proto::Box::Cube (int a_size) inline static
Cube Function Creates the Box [Point::Zeros(), Point::Ones()*(a_size-1)], a cube in of side length a_size
Parameters
a_size side length
References define().
Point Proto::Box::low () const inline
Access Low Corner.
This function returns by value; a Box cannot be altered through the output of low().
References m_low.
Referenced by adjCellHi(), adjCellLo(), Proto::coarseCoef(), Proto::BoxData< T, C, D, E >::dataPtr(), Proto::Stencil< double >::domain(), Proto::SimpleGeometry::getCornerLocations(), Proto::Stencil< double >::indexRange(), Proto::operator<<(), Proto::Stencil< double >::range(), Proto::Stencil< double >::spanPoint(), and Proto::InterpStencil< T >::spanPoint().
Point Proto::Box::high () const inline
Access High Corner.
This function returns by value; a Box cannot be altered through the output of high().
References m_high.
Referenced by adjCellHi(), adjCellLo(), Proto::InterpStencil< T >::close(), Proto::coarseCoef(), Proto::Stencil< double >::domain(), Proto::SimpleGeometry::getCornerLocations(), Proto::Stencil< double >::indexRange(), Proto::operator<<(), Proto::Stencil< double >::range(), Proto::Stencil< double >::spanPoint(), and Proto::InterpStencil< T >::spanPoint().
std::size_t Proto::Box::size (unsigned char a_dim) const inline
Edge Size.
Returns the "edge length" of this Box on a given axis
/param a_dim direction axis in [0,DIM)
Example:
//DIM=2
using namespace Proto;
Box B(Point::Zeros(), Point({1,3}));
B.print(); //prints [(0,0),(1,3)]
std::cout << B.size(0) << std::endl; //prints 2
std::cout << B.size(1) << std::endl; //prints 4
Referenced by Proto::InterpStencil< T >::define(), Proto::BoxIterator::done(), Proto::ebforallInPlace(), Proto::ebforallInPlace_i(), Proto::BoxData< T, C, D, E >::operator-=(), and Proto::BoxData< T, C, D, E >::size().
CUDA_DECORATION std::size_t Proto::Box::size () const inline
Volumetric Size.
Returns the "volume" (in number of points) of this box.
Example:
//DIM=2
using namespace Proto;
Box B(Point::Zeros(), Point({1,3}));
B.print(); //prints [(0,0),(1,3)]
std::cout << B.size() << std::endl; //prints 8 (=2*4)
References m_size.
bool Proto::Box::contains (const Point & a_pt) const inline
Contains Point Query.
Checks if a_pt is inside of *this. Note that this->low() and this->high() are both considered inside *this
Example:
//DIM=2
using namespace Proto;
Box B(Point::Zeros(), Point({1,3}));
std::cout << B.contains(Point({0,0})) << std::endl; //prints true
std::cout << B.contains(Point({1,1})) << std::endl; //prints true
std::cout << B.contains(Point({1,3})) << std::endl; //prints true
std::cout << B.contains(Point({1,4})) << std::endl; //prints false
Referenced by Proto::InterpStencil< T >::get(), Proto::Stencil< double >::operator()(), Proto::InterpStencil< T >::operator()(), Proto::BoxData< T, C, D, E >::operator-=(), and Proto::BoxData< T, C, D, E >::var().
bool Proto::Box::contains (const Box & a_rhs) const inline
Contains Box Query.
Check if Bx a_rhs is a subset of *this. Returns true even if a_rhs is not a proper subset. Equivalent to this->contains(a_rhs.low()) && this->contains(a_rhs.high()
Example:
//DIM=2
using namespace Proto;
Box B0(Point({0,0}),Point({3,3}));
Box B1(Point({1,1}),Point({2,2}));
Box B2(Point({1,1}),Point({4,4}));
Box B2(Point({-1,-1}),Point({2,2}));
std::cout << B0.contains(B0) << std::endl; //prints true
std::cout << B0.contains(B1) << std::endl; //prints true
std::cout << B0.contains(B2) << std::endl; //prints false
std::cout << B0.contains(B3) << std::endl; //prints false
bool Proto::Box::onBoundary (const Point & a_p) const inline
Point on Boundry Query.
Check of a_p is part of the boundry of this Bx.
Parameters
a_p A Point
bool Proto::Box::empty () const inline
Empty Query.
Check if *this contains no Points
References m_size.
unsigned int Proto::Box::index (const Point & a_pt) const inline
Point to Linear Index.
Returns a linear index in [0,this->size()) associated with a_pt. Fails by assertion if a_pt is not inside *this. Indices start at this->low() which has an index of 0. Indices increase fastest in dimension 0 and slowest in dimension DIM-1. this->high() has an index of this->size()-1
Parameters
a_pt a Point inside *this
Referenced by Proto::BoxIterator::BoxIterator(), Proto::InterpStencil< T >::get(), Proto::InterpStencil< T >::operator()(), and Proto::BoxData< T, C, D, E >::operator-=().
Point Proto::Box::operator[] (unsigned int a_index) const inline
Access Point by Index.
Return a Point associated with a_index . This is the inverse of the index(Point) function.
Parameters
a_index an index in [0,this->size())
static CUDA_DECORATION unsigned int Proto::Box::sindex (Point a_pt, Point a_low, Point a_high) inline static
for stencil internals
static CUDA_DECORATION int Proto::Box::soffset (const Point & a_pt, const Point & a_low, const Point & a_high) inline static
Box Proto::Box::operator& (const Box & a_rightBox) const inline
Intersection Operator.
Returns a new Box which is the intersection of *this and *a_rightBox.
Parameters
a_rightBx Another Bx
Example:
//DIM=2
using namespace Proto;
Box B0 = Box::Cube(3);
Box B1 = Box::Cube(3).shift(Point::Ones());
Box B2 = B0 & B1;
B0.print(); //prints [(0,0),(2,2)]
B1.print(); //prints [(1,1),(3,3)]
B2.print(); //prints [(1,1),(2,2)]
void Proto::Box::operator&= (const Box & a_rightBox) inline
Box Proto::Box::operator& (Point a_pt) const inline
Add Point Operator.
Returns a new Bx which has been grown such that it contains a_pt.
Parameters
a_pt Point to be added
bool Proto::Box::operator== (const Box & a_rhsBox) const inline
Equality Operator.
Two Boxes are considered equal if they have identical (==) low() and high()
Parameters
a_rhsBox A Box to test equality with
bool Proto::Box::operator!= (const Box & a_rhsBox) const inline
Inequality Operator.
Point Proto::Box::operator% (const Point & a_pt) const inline
Modulus Operator.
Convenience operator for Bx::mod(...).
Parameters
a_pt A Point to mod by
Box Proto::Box::shift (int a_direction, int a_offset) const inline
Shift Transformation.
Creates a new Box shifted in a_direction by a_offset units relative to *this.
Parameters
a_direction an int in /f$[0,DIM)/f$ specifying a direction
a_offset number of points to offset. Use a negative value for a negative offset.
Example:
//DIM=2
using namespace Proto;
Box B1 = Box::Cube(2);
Box B2 = B1.shift(0,1);
Box B3 = B1.shift(1,-1);
B1.print(); //prints [(0,0), (1,1)]
B2.print(); //prints [(1,0), (2,1)]
B3.print(); //prints [(0,-1), (1,0)]
Referenced by Proto::Stencil< double >::indexDomain(), Proto::Stencil< double >::range(), and Proto::BoxData< T, C, D, E >::shift().
Box Proto::Box::shift (const Point & a_pt) const inline
Point Shift Transformation.
Creates a new Box shifted by a_pt relative to *this. New Box is: [low() + a_pt, high() + a_pt]
Parameters
a_pt shift offset
Example:
//DIM=2
using namespace Proto;
Box B1(Point::Zeros(),Point::Ones());
Box B2 = B1.shift(Point({2,-3}));
B1.print(); //prints [(0,0), (1,1)]
B2.print(); //prints [(2,-3), (3,-2)]
Box Proto::Box::grow (const Point & a_pt) const inline
Anisotropic Grow Operation.
Returns the reshaped Box: [low() - a_pt, high() + a_pt]
Parameters
a_pt growth offset
Example:
//DIM=2
using namespace Proto;
Box B0(Point::Zeros(),Point::Ones()*3);
Box B1 = B0.grow(Point({-1,1})); //shrink in dimension 0, grow in dimension 1
B0.print(); //prints [(0, 0), (3, 3)]
B1.print(); //prints [(1, -1), (2, 4)]
Referenced by Proto::EBGraph::getAllVoFsWithinRadius(), and grow().
Box Proto::Box::grow (int idir, int igrow) const inline
grows both low and high
References Proto::Point::Basis(), and grow().
Box Proto::Box::growHi (int idir, int igrow) const inline
grows only high side
References Proto::Point::Basis(), m_high, and m_low.
Box Proto::Box::growLo (int idir, int igrow) const inline
grows only low side
References Proto::Point::Basis(), m_high, and m_low.
Box Proto::Box::grow (int a_numpoints) const inline
Isotropic Grow Operation.
Returns a new Box which is larger in every direction by a_numpoints units. If a_numpoints is negative, the box will shrink.
Parameters
a_numpoints number of points to grow by in each direction
Example:
//DIM=2
using namespace Proto;
Box B0(Point::Zeros(),Point::Ones());
Box B1 = B0.grow(3);
Box B2 = B1.grow(-2);
B0.print(); //prints [(0, 0), (1, 1)]
B1.print(); //prints [(-3,-3), (4, 4)]
B2.print(); //prints [(-1,-1), (2, 2)]
Box Proto::Box::coarsen (const Point & a_pt) const inline
Anisotropic Coarsen Operation.
Returns a new Box coarsened in each direction according to a_pt. Fails if user tries to coarsen using a non-positive ratio.
Parameters
a_pt Coarsening ratios
Example:
//DIM=2
using namespace Proto;
Box B0 = Box::Cube(4);
//coarsen in only the 1 direction
Box B1 = B0.coarsen(Point({1,2}));
B1.print(); //prints [(0,0),(3,1)]
Referenced by coarsenable().
Box Proto::Box::coarsen (unsigned int a_ratio) const inline
Isotropic Coarsen Operation.
Returns a new Box coarsened by a factor of a_numpoints. Fails if user tries to coarsen using a non-positive ratio. If the limits of *this are not multiples of the coarsening ratio (e.g. if this-> coarsenable() != true) the resulting Bx is not guaranteed to be a subset of *this. In this situation, use Bx::taperCoarsen
Parameters
a_ratio Coarsening ratio
Example:
//DIM=2
using namespace Proto;
Box B0 = Box::Cube(4);
Box B1 = B0.coarsen(2);
B0.print(); //prints [(0, 0), (3, 3)]
B1.print(); //prints [(0, 0), (1, 1)]
Box B2 = Box::Cube(3).shift(Point::Ones()*2);
Box B3 = B2.coarsen(2);
B2.print(); //prints [(2, 2), (4, 4)]
B3.print(); //prints [(1, 1), (2, 2)]
bool Proto::Box::coarsenable (const int & a_ratio) const inline
Coarsenable Query.
Returns true if *this will coarsen normally by a given ratio.
Parameters
a_ratio Coarsening ratio
References coarsen(), Proto::Point::Ones(), and refine().
Box Proto::Box::taperCoarsen (const Point & a_ref) inline
This function is identical to Bx::coarsen when Bx::coarsenable() is true. For non-coarsenable Boxes, the new Box's limits are rounded such that the result Is always a subset of *this. Specifically, the lower limits are always rounded UP.
Parameters
a_ref Coarsening ratio
References Box(), m_high, and m_low.
Referenced by Proto::Stencil< double >::indexDomain(), and Proto::Stencil< double >::indexRange().
Box Proto::Box::refine (const Point & a_pt) const inline
Anisotropic Refine Operation.
Returns a new Box refined in each direction according to a_pt.
Parameters
a_pt Refinement ratios
Example:
//DIM=2
using namespace Proto;
Box B0 = Box::Cube(2);
Box B1 = B0.refine(Point({1,2}));
B0.print(); //prints [(0, 0), (1, 1)]
B1.print(); //prints [(0, 0), (1, 3)]
Referenced by coarsenable(), and Proto::EBGraph::getVoFsThatCoarsenTo().
Box Proto::Box::refine (unsigned int a_ratio) const inline
Isotropic Refine Operation.
Returns a new Box refined in all direcitons by a_numpoints.
Parameters
a_ratio Refinement ratio
Example:
//DIM=2
using namespace Proto;
Box B0 = Box::Cube(2);
Box B1 = B0.refine(2);
B0.print(); //prints [(0, 0), (1, 1)]
B1.print(); //prints [(0, 0), (3, 3)]
Box B2 = Box::Cube(2).shift(Point::Ones());
Box B3 = B2.coarsen(2);
B2.print(); //prints [(1, 1), (2, 2)]
B3.print(); //prints [(2, 2), (5, 5)]
Box Proto::Box::flatten (const int a_dir, bool a_upper = false) const inline
Flatten.
Returns a copy of *this with dimension a_dir flattened to a thickness of 1. Useful for creating Boxes of dimensionality less than DIM (e.g. a plane in 3D)
Parameters
a_dir Direction to flatten
a_upper Flatten upwards? Example:
//DIM=3
using namespace Proto;
Box B0 = Box::Cube(4).shift(Point::Ones());
Box B1 = B0.flatten(2);
Box B2 = B0.flatten(2,true);
B0.print(); //prints [(1, 1, 1), (4, 4, 4)]
B1.print(); //prints [(1, 1, 1), (4, 4, 1)]
B2.print(); //prints [(1, 1, 4), (4, 4, 4)]
Box Proto::Box::adjCellLo (int a_idir, int a_length) const inline
References Box(), high(), and low().
Box Proto::Box::adjCellHi (int a_idir, int a_length) const inline
References Box(), high(), and low().
Box Proto::Box::edge (const Point & a_dir) const inline
Edge.
Returns the subset on the boundary of *this in a given direction. Very handy for adjacency and boundary based computations.
Parameters
a_dir Direction of desired edge with respect to the cell center of *this
Examples:
this->edge(Point::Basis(0,+1)); //returns the upper face along the 0 axis.
this->edge(Point::Basis(0,-1)); //returns the lower face along the 0 axis.
this->edge(Point::Ones());      //returns m_high
this->edge(Point::Ones(-1);     //returns m_low
this->edge(Point(1,-1,0,...,0); //returns the 1D line of points which forms the intersection
//of the upper face along the 0 axis and the lower face along the 1 axis.
Box Proto::Box::extrude (int a_dir, int a_dist = 1, bool a_upper = true) const inline
Extrude.
Returns a new Bx with the a_dir direction extruded a distance a_dist . By default, the extrusion is upwards. If a_up is false, extrudes downwards. Useful computing e.g. "face" boxes.
Parameters
a_dir Axis to extrude along
a_dist (Optional) Distance to extrude (default: 1)
a_upper (Optional) Extrude upwards? (default: true)
Example:
//DIM=3
using namespace Proto;
Box B0 = Box::Cube(4).shift(Point::Ones());
Box B1 = B0.extrude(2,3);
Box B2 = B0.extrude(2,3,true);
B0.print(); //prints [(1, 1, 1), (4, 4, 4)]
B1.print(); //prints [(1, 1, -2), (4, 4, 4)]
B2.print(); //prints [(1, 1, 1), (4, 4, 7)]
BoxIterator Proto::Box::begin () const inline
Iterator Begin.
See documentation for Proto::BoxIterator for a basic usage example.
Referenced by Proto::InterpStencil< T >::close(), Proto::EBGraph::getAllVoFsWithinRadius(), and Proto::EBGraph::getVoFsThatCoarsenTo().
BoxIterator Proto::Box::end () const inline
Iterator End.
See documentation for Proto::BoxIterator for a basic usage example.
Referenced by Proto::InterpStencil< T >::close(), Proto::EBGraph::getAllVoFsWithinRadius(), and Proto::EBGraph::getVoFsThatCoarsenTo().
BoxIterator Proto::Box::rbegin () const inline
Iterator Reverse Begin.
See documentation for Proto::BoxIterator for a basic usage example.
BoxIterator Proto::Box::rend () const inline
Iterator Reverse End.
See documentation for Proto::BoxIterator for a basic usage example.
Point Proto::Box::mod (const Point & a_pt) const inline
Point Modulus Operation.
Returns the periodic image of a_pt that is inside *this.
Parameters
a_pt Point divisor
Example:
//DIM = 2;
using namespace Proto;
Box B = Box::Cube(3);
std::cout << B.mod(Point({3,3})) << std::endl; //prints (1,1)
std::cout << B.mod(Point({-1,-1})) << std::endl; //prints (2,2)
void Proto::Box::print () const inline
Print.
Prints *this using the format [low, high]
void Proto::Box::recomputeSize () inline private
Used to reevaluate the size of the box when it is changed.
Member Data Documentation
Point Proto::Box::m_low private
Point object containing the lower bounds of the Box.
Referenced by growHi(), growLo(), low(), and taperCoarsen().
Point Proto::Box::m_high private
Point object containing the upper bounds of the Box.
Referenced by growHi(), growLo(), high(), and taperCoarsen().
int Proto::Box::m_size private
"Volume" of the box.
Referenced by empty(), and size().
The documentation for this class was generated from the following file:
Proto_Box.H