Proto: Proto::CellNode Class Reference
Proto::CellNode Class Reference
#include <Proto_EBGraph.H>
Classes
struct IrrGraphNode
Public Member Functions
template<CENTERING cent>
void getFaceInfo (vector< EBIndex< cent > > &a_faces, const int &a_dir, const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd, const Box &a_domain) const
template<CENTERING cent>
void setFaceStuff (EBIndex< cent > &a_face, const int &a_inputIndex, const int &a_otherIndex, const Point &a_inputIV, const Point &a_otherIV, const Side::LoHiSide &a_sd, const Box &a_domain) const
CellNode ()
~CellNode ()
bool isCovered () const
bool isRegular () const
bool isIrregular () const
void defineAsRegular ()
void defineAsFullIrregular (const Point &a_pt, const Box &a_domain)
void defineAsIrregular ()
void defineAsCovered ()
vector< EBIndex< XFACE > > getXFaces (const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd, const Box &a_domain) const
vector< EBIndex< YFACE > > getYFaces (const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd, const Box &a_domain) const
vector< EBIndex< CELL > > getVoFs (const Point &a_iv) const
vector< EBIndex< BOUNDARY > > getCutFaces (const Point &a_iv) const
return vofs labelled as irregular (only places where an EB can happen)
CellNode (const CellNode &a_ebin)
CellNode & operator= (const CellNode &a_ebin)
size_t linearSize () const
for serialization (chombo uses this in parallel code)
void linearIn (const char *a_buf)
for serialization (chombo uses this in parallel code)
void linearOut (char *a_buf) const
for serialization (chombo uses this in parallel code)
Static Public Member Functions
static bool constantMemorySize ()
for serialization (chombo uses this in parallel code)
Public Attributes
vector< IrrGraphNode > * m_cellList
Detailed Description
This is a list showing the connectivity of a given cell. This has the special property of also being able to set itself to regular or covered by setting the current nodeimplem pointer to 1 or 0.
Constructor & Destructor Documentation
Proto::CellNode::CellNode () inline
References m_cellList.
Proto::CellNode::~CellNode () inline
References isIrregular(), and m_cellList.
Proto::CellNode::CellNode (const CellNode & a_ebin) inline
Member Function Documentation
template<CENTERING cent> void Proto::CellNode::getFaceInfo (vector< EBIndex< cent > > & a_faces, const int & a_dir, const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd, const Box & a_domain) const inline
template<CENTERING cent> void Proto::CellNode::setFaceStuff (EBIndex< cent > & a_face, const int & a_inputIndex, const int & a_otherIndex, const Point & a_inputIV, const Point & a_otherIV, const Side::LoHiSide & a_sd, const Box & a_domain) const inline
bool Proto::CellNode::isCovered () const inline
Return true if the node is covered (m_cellList==0).
References m_cellList.
Referenced by isIrregular(), linearSize(), and operator=().
bool Proto::CellNode::isRegular () const inline
Return true if the node is regular.
References m_cellList.
Referenced by isIrregular(), linearOut(), linearSize(), and operator=().
bool Proto::CellNode::isIrregular () const inline
Return true if the node is neither regular or covered.
References isCovered(), and isRegular().
Referenced by defineAsCovered(), defineAsFullIrregular(), defineAsIrregular(), defineAsRegular(), linearOut(), and ~CellNode().
void Proto::CellNode::defineAsRegular () inline
Set Node to regular. If previously set to irregular, deletes their memory.
References isIrregular(), and m_cellList.
Referenced by linearIn(), and operator=().
void Proto::CellNode::defineAsFullIrregular (const Point & a_pt, const Box & a_domain) inline
References Proto::Point::Basis(), Proto::Box::contains(), Proto::ebp_index(), Proto::EBIndex< cent >::getRefinedRegular(), isIrregular(), m_cellList, Proto::SideIterator::ok(), and Proto::sign().
void Proto::CellNode::defineAsIrregular () inline
References isIrregular(), and m_cellList.
Referenced by linearIn(), and operator=().
void Proto::CellNode::defineAsCovered () inline
Set Node to covered. If previously set to irregular, deletes their memory.
References isIrregular(), and m_cellList.
Referenced by linearIn(), and operator=().
vector<EBIndex<XFACE> > Proto::CellNode::getXFaces (const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd, const Box & a_domain) const inline
Get the faces in the direction and side for the vof in the list. if the vof's cell index is not found in the list, abort. Use the input vof's grid index for a the grid index of the list.
vector<EBIndex<YFACE> > Proto::CellNode::getYFaces (const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd, const Box & a_domain) const inline
vector< EBIndex<CELL> > Proto::CellNode::getVoFs (const Point & a_iv) const inline
Return all the vofs in the list, using the input intvect for the gridIndex
vector<EBIndex<BOUNDARY> > Proto::CellNode::getCutFaces (const Point & a_iv) const inline
return vofs labelled as irregular (only places where an EB can happen)
CellNode& Proto::CellNode::operator= (const CellNode & a_ebin) inline
References defineAsCovered(), defineAsIrregular(), defineAsRegular(), isCovered(), isRegular(), and m_cellList.
static bool Proto::CellNode::constantMemorySize () inline static
for serialization (chombo uses this in parallel code)
size_t Proto::CellNode::linearSize () const inline
for serialization (chombo uses this in parallel code)
References isCovered(), isRegular(), and m_cellList.
void Proto::CellNode::linearIn (const char * a_buf) inline
for serialization (chombo uses this in parallel code)
References defineAsCovered(), defineAsIrregular(), defineAsRegular(), and m_cellList.
void Proto::CellNode::linearOut (char * a_buf) const inline
for serialization (chombo uses this in parallel code)
References isIrregular(), isRegular(), and m_cellList.
Member Data Documentation
vector<IrrGraphNode>* Proto::CellNode::m_cellList
The connectivity data at this point. If m_cellList == 0, node is covered. If m_cellList == 1, node is regular and parent is single-valued. otherwise, it is a real list (node may still be regular).
Referenced by CellNode(), defineAsCovered(), defineAsFullIrregular(), defineAsIrregular(), defineAsRegular(), isCovered(), isRegular(), linearIn(), linearOut(), linearSize(), operator=(), and ~CellNode().
The documentation for this class was generated from the following file:
Proto_EBGraph.H