Proto: Proto::InterpStencil< T > Class Template Reference
Proto::InterpStencil< T > Class Template Reference
Stencil Operations
Interpolation Stencil.
#include <Proto_Stencil.H>
Public Member Functions
InterpStencil ()
Default Constructor.
InterpStencil (int a_ratio)
Isotropic Constructor.
InterpStencil (Point a_ratio)
Anisotropic Constructor.
void define (Point a_ratio)
Define.
void close ()
Stencil< T > & operator() (Point a_p)
Get Read-Write Stencil Subcomponent.
const Stencil< T > & get (Point a_p) const
Get Read-Only Stencil Subcomponent.
Box span ()
Span.
Point spanPoint ()
template<unsigned int C, unsigned char D, unsigned char E>
LazyStencil< T, C, D, E > operator() (const BoxData< T, C, D, E > &a_src, T a_scale=1) const
Lazy Apply.
template<unsigned int C, unsigned char D, unsigned char E>
LazyStencil< T, C, D, E > operator() (const BoxData< T, C, D, E > &a_src, Box a_box, T a_scale=1) const
Lazy Apply.
Box kernel () const
Return Shift Kernel.
Point ratio () const
Return Destination Refinement Ratio.
std::vector< Stencil< T >
>::iterator begin ()
Iterate Over Stencil Components.
std::vector< Stencil< T >
>::iterator end ()
Iterate Over Stencil Components.
bool empty ()
Empty Query.
unsigned long long int size () const
Size Query.
Static Public Member Functions
static InterpStencil< T > PiecewiseConstant (Point a_ratio)
Piecewise Constant Interpolation.
static InterpStencil< T > PiecewiseLinear (Point a_ratio)
Piecewise Linear Interpolation.
static InterpStencil< T > Quadratic (int a_ratio)
Piecewise Linear Interpolation.
static InterpStencil< T > Build (int a_shiftMax, Box a_shiftKernel, int a_order, int a_refRatio)
Build General High-Order Interpolation Stencil.
static InterpStencil< T > Build (std::vector< Point > &a_shifts, int a_maxOrder, int a_refRatio)
Build General High-Order Interpolation Stencil.
static InterpStencil< T > Build (std::vector< Point > &a_shifts, const std::vector< Point > &a_orders, int a_refRatio)
Build General High-Order Interpolation Stencil.
Private Attributes
Point m_r
Destination refinement ratio shared by all Stencil components.
Box m_k
Kernel of destination shifts.
std::vector< Stencil< T > > m_s
Array of Stencils.
bool m_closed = false
Closed boolean. True if shifts / refratios of Stencils have been set (e.g. by calling close())
Detailed Description
template<class T>
class Proto::InterpStencil< T >
Interpolation Stencil.
InterpStencil is a convenient abstraction which encapsulates the functionality of an operation in which the destination refinement is non-trivial. This kind of operation can be done with normal Stencil objects, however for a destination refinement of R, an array of R^DIM Stencils will be needed in general.
Constructor & Destructor Documentation
template<class T> Proto::InterpStencil< T >::InterpStencil () inline
Default Constructor.
References Proto::InterpStencil< T >::m_closed.
Member Function Documentation
template<class T> void Proto::InterpStencil< T >::close () inline
References Proto::Box::begin(), Proto::Stencil< T >::destRatio(), Proto::Stencil< T >::destShift(), Proto::Box::end(), Proto::Box::high(), Proto::InterpStencil< T >::m_closed, Proto::InterpStencil< T >::m_k, and Proto::Point::Ones().
template<class T> Point Proto::InterpStencil< T >::spanPoint () inline
References Proto::Box::high(), Proto::Box::low(), and Proto::InterpStencil< T >::span().
Member Data Documentation
template<class T> Point Proto::InterpStencil< T >::m_r private
Destination refinement ratio shared by all Stencil components.
Referenced by Proto::InterpStencil< T >::ratio().
template<class T> Box Proto::InterpStencil< T >::m_k private
Kernel of destination shifts.
Referenced by Proto::InterpStencil< T >::close(), Proto::InterpStencil< T >::define(), Proto::InterpStencil< T >::get(), Proto::InterpStencil< T >::kernel(), and Proto::InterpStencil< T >::operator()().
template<class T> std::vector<Stencil<T> > Proto::InterpStencil< T >::m_s private
Array of Stencils.
Referenced by Proto::InterpStencil< T >::begin(), Proto::InterpStencil< T >::define(), Proto::InterpStencil< T >::empty(), Proto::InterpStencil< T >::end(), Proto::InterpStencil< T >::get(), Proto::InterpStencil< T >::operator()(), Proto::InterpStencil< T >::size(), and Proto::InterpStencil< T >::span().
template<class T> bool Proto::InterpStencil< T >::m_closed = false private
Closed boolean. True if shifts / refratios of Stencils have been set (e.g. by calling close())
Referenced by Proto::InterpStencil< T >::close(), Proto::InterpStencil< T >::define(), Proto::InterpStencil< T >::InterpStencil(), and Proto::InterpStencil< T >::operator()().
The documentation for this class was generated from the following file:
Proto_Stencil.H