Proto: Stencil Operations
Stencil Operations
Classes
class Proto::Shift
Stencil Shift.
class Proto::BoxData< T, C, D, E >
Multidimensional Rectangular Array.
class Proto::Stencil< T >
A Linear Stencil Operation.
class Proto::InterpStencil< T >
Interpolation Stencil.
Macros
#define PRroto_stencildefs
Functions
template<unsigned int C, unsigned char D, unsigned char E>
void Proto::Stencil< T >::apply (const BoxData< T, C, D, E > &a_src, BoxData< T, C, D, E > &a_dest, const Box &a_bx, bool a_initToZero=false, const T a_scale=1) const
Apply Stencil Helper function.
Proto::InterpStencil< T >::InterpStencil (int a_ratio)
Isotropic Constructor.
Proto::InterpStencil< T >::InterpStencil (Point a_ratio)
Anisotropic Constructor.
void Proto::InterpStencil< T >::define (Point a_ratio)
Define.
Stencil< T > & Proto::InterpStencil< T >::operator() (Point a_p)
Get Read-Write Stencil Subcomponent.
const Stencil< T > & Proto::InterpStencil< T >::get (Point a_p) const
Get Read-Only Stencil Subcomponent.
Box Proto::InterpStencil< T >::span ()
Span.
template<unsigned int C, unsigned char D, unsigned char E>
LazyStencil< T, C, D, E > Proto::InterpStencil< T >::operator() (const BoxData< T, C, D, E > &a_src, T a_scale=1) const
Lazy Apply.
template<unsigned int C, unsigned char D, unsigned char E>
LazyStencil< T, C, D, E > Proto::InterpStencil< T >::operator() (const BoxData< T, C, D, E > &a_src, Box a_box, T a_scale=1) const
Lazy Apply.
Box Proto::InterpStencil< T >::kernel () const
Return Shift Kernel.
Point Proto::InterpStencil< T >::ratio () const
Return Destination Refinement Ratio.
std::vector< Stencil< T >
>::iterator Proto::InterpStencil< T >::begin ()
Iterate Over Stencil Components.
std::vector< Stencil< T >
>::iterator Proto::InterpStencil< T >::end ()
Iterate Over Stencil Components.
bool Proto::InterpStencil< T >::empty ()
Empty Query.
unsigned long long int Proto::InterpStencil< T >::size () const
Size Query.
double Proto::coarseCoef (Point p, Point s, double h)
double Proto::fineCoef (Point p, Point s, double h, int refRatio)
int Proto::dgemv_ (char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *)
int Proto::dgemm_ (char *, char *, int *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *)
int Proto::dgetri_ (int *, double *, int *, int *, double *, int *, int *)
int Proto::dgetrf_ (int *, int *, double *, int *, int *, int *)
void Proto::Stencil< T >::augment (T a_coef, Point a_offset)
Augment Stencil.
template<unsigned int C, unsigned char D, unsigned char E>
void Proto::Stencil< T >::hostApply (const BoxData< T, C, D, E > &a_src, BoxData< T, C, D, E > &a_dest, const Box &a_box, bool a_initToZero, T a_scale) const
Variables
Point Proto::Shift::m_shift
Friends
template<typename TT , unsigned int C, unsigned char D, unsigned char E>
class Proto::Stencil< T >::BoxData
template<typename TT , unsigned int C, unsigned char D, unsigned char E>
BoxData< TT, C, D, E > & Proto::Stencil< T >::operator|= (BoxData< TT, C, D, E > &a_dest, LazyStencil< TT, C, D, E > &&a_op)
template<typename TT , unsigned int C, unsigned char D, unsigned char E>
BoxData< TT, C, D, E > & Proto::Stencil< T >::operator+= (BoxData< TT, C, D, E > &a_dest, LazyStencil< TT, C, D, E > &&a_op)
Non-Member Functions
template<typename T >
Stencil< T > Proto::operator* (T a_coef, Shift a_shift)
Coefficient Shift Product "Constructor".
template<typename T >
Stencil< T > Proto::operator* (T a_coef, const Stencil< T > a_stencil)
Scalar Multiplication of Stencil Coefficients.
template<typename T , unsigned int C, unsigned char D, unsigned char E>
BoxData< T, C, D, E > & Proto::operator|= (BoxData< T, C, D, E > &a_dest, LazyStencil< T, C, D, E > &&a_op)
Application by Replacement.
template<class T , unsigned int C, unsigned char D, unsigned char E>
BoxData< T, C, D, E > & Proto::operator+= (BoxData< T, C, D, E > &a_dest, LazyStencil< T, C, D, E > &&a_op)
Application by Increment.
Constructors
Proto::Shift::Shift ()
Default Constructor.
Proto::Shift::Shift (const Point &a_pt)
Point Constructor.
template<typename... vals>
Proto::Shift::Shift (vals...args)
Variadic Constructor.
Methods
static Shift Proto::Shift::Basis (int a_dir, int a_scale=1)
Basis Shift.
static Shift Proto::Shift::Zeros ()
Zero Shift.
static Shift Proto::Shift::Ones (int a_scale=1)
Unit Shift.
Point & Proto::Shift::shift ()
Get Shift Point.
template<typename T >
Stencil< T > Proto::Shift::operator* (T a_coef) const
Scalar Multiplication.
Shift Proto::Shift::operator* (const Shift &a_shift) const
Convolution.
int & Proto::Shift::operator[] (int a_dir)
Componentwise Access.
Constructors
Proto::Stencil< T >::Stencil ()
Default Constructor.
Proto::Stencil< T >::Stencil (Shift a_shift, T a_coef, Point a_destRefratio=Point::Ones(), Point a_destShift=Point::Zeros(), Point a_srcRefratio=Point::Ones())
General Constructor.
Operators
Stencil< T > Proto::Stencil< T >::operator* (const Stencil< T > &a_stencil) const
Stencil Composition.
Stencil< T > Proto::Stencil< T >::operator* (const T a_coef) const
Scalar Multiplication.
void Proto::Stencil< T >::operator*= (const Stencil< T > &a_stencil)
In Place Stencil Composition.
void Proto::Stencil< T >::operator*= (const T a_coef)
In Place Scalar Multiplication.
Stencil< T > Proto::Stencil< T >::operator+ (const Stencil< T > &a_stencil) const
Stencil Addition.
Stencil< T > Proto::Stencil< T >::operator- (const Stencil< T > &a_stencil) const
Stencil Subtraction (Convenience)
void Proto::Stencil< T >::operator+= (const Stencil< T > &a_stencil)
In Place Stencil Addition.
void Proto::Stencil< T >::operator-= (const Stencil< T > &a_stencil)
In Place Stencil Subtraction.
Accessors and Queries
bool Proto::Stencil< T >::operator== (Stencil< T > &a_stencil) const
bool Proto::Stencil< T >::operator!= (Stencil< T > &a_stencil) const
Inquality Operator.
const std::vector< T > & Proto::Stencil< T >::coefs () const
Get Vector of Coefficients.
const std::vector< Point > & Proto::Stencil< T >::offsets () const
Get Vector of Offsets.
unsigned long long int Proto::Stencil< T >::size () const
Size.
Box Proto::Stencil< T >::span () const
Span.
Point Proto::Stencil< T >::spanPoint () const
Span.
unsigned long long int Proto::Stencil< T >::numFlops (const Box &a_box) const
Point Proto::Stencil< T >::ghost () const
Ghost.
Point & Proto::Stencil< T >::srcRatio ()
Get Source Refinement Ratio.
const Point & Proto::Stencil< T >::srcRatio () const
Get Source Refinement Ratio (Const)
Point & Proto::Stencil< T >::destRatio ()
Get Destination Refinement Ratio.
const Point & Proto::Stencil< T >::destRatio () const
Get Destination Refinement Ratio (Const)
Point & Proto::Stencil< T >::destShift ()
Get Destination Shift.
const Point & Proto::Stencil< T >::destShift () const
Get Destination Shift (Const)
Stencil Binding and Application
template<unsigned int C, unsigned char D, unsigned char E>
LazyStencil< T, C, D, E > Proto::Stencil< T >::operator() (const BoxData< T, C, D, E > &a_src, T a_scale=1) const
Operate on BoxData.
template<unsigned int C, unsigned char D, unsigned char E>
LazyStencil< T, C, D, E > Proto::Stencil< T >::operator() (const BoxData< T, C, D, E > &a_src, Box a_box, T a_scale=1) const
Operate on BoxData (Overload with Box Input)
Utility
void Proto::Stencil< T >::transpose (unsigned char a, unsigned char b)
Transpose Stencil.
Box Proto::Stencil< T >::indexRange (Box a_domain) const
Get Max Index Range.
Box Proto::Stencil< T >::indexDomain (Box a_range) const
Get Max Index Domain.
Box Proto::Stencil< T >::range (Box a_domain) const
Get Max Range Box.
Box Proto::Stencil< T >::domain (Box a_range) const
Get Min Domain Box.
void Proto::Stencil< T >::print () const
Print.
Detailed Description
Macro Definition Documentation
#define PRroto_stencildefs
Function Documentation
Proto::Shift::Shift () inline
Default Constructor.
Referenced by Proto::Shift::Ones(), Proto::Shift::operator*(), Proto::Stencil< T >::operator*=(), and Proto::Shift::Zeros().
Proto::Shift::Shift (const Point & a_pt) inline explicit
Point Constructor.
Builds a Shift from a Point
Parameters
a_pt Point to base this Shift on
References Proto::Shift::m_shift.
template<typename... vals> Proto::Shift::Shift (vals... args) inline explicit
Variadic Constructor.
More or less identical to the variadic Point constructor. Builds a Shift using the first DIM arguments and ignores the rest.
Parameters
args At least DIM int arguments, the first DIM of which define *this
static Shift Proto::Shift::Basis (int a_dir, int a_scale = 1) inline static
Basis Shift.
Shortcut for Shift(Point::Basis(...))
Parameters
a_dir Direction of basis vector in [0,DIM)
a_scale (OptionL) Amount to scale the basis vector by. (Default 1).
static Shift Proto::Shift::Zeros () inline static
Zero Shift.
Shortcut for Shift(Point::Zeros())
References Proto::Shift::Shift(), and Proto::Point::Zeros().
static Shift Proto::Shift::Ones (int a_scale = 1) inline static
Unit Shift.
Shortcut for Shift(Point::Ones(...))
Parameters
a_scale (Optional) Used to scale the default output of (1,1,...,1).
References Proto::Point::Ones(), and Proto::Shift::Shift().
Point& Proto::Shift::shift () inline
Get Shift Point.
References Proto::Shift::m_shift.
template<typename T > Stencil<T> Proto::Shift::operator* (T a_coef) const inline
Scalar Multiplication.
Generates a Stencil<T> from the product of a scalar T coefficient and a Shift. This operator is what allows for a fluid Stencil construction syntax:
Example:
// DIM == 1
Stencil<double> = 1.0*Shift(-1) - 2.0*Shift(0) + 1.0*Shift(1);
Shift Proto::Shift::operator* (const Shift & a_shift) const inline
Convolution.
The product of two Shift objects is defined as their sum.
References Proto::Shift::m_shift, and Proto::Shift::Shift().
int& Proto::Shift::operator[] (int a_dir) inline
Componentwise Access.
References PROTO_ASSERT.
template<typename T > Proto::Stencil< T >::Stencil ()
Default Constructor.
template<typename T> Proto::Stencil< T >::Stencil (Shift a_shift, T a_coef, Point a_destRefratio = Point::Ones(), Point a_destShift = Point::Zeros(), Point a_srcRefratio = Point::Ones())
General Constructor.
Creates a Stencil with a single shift and coefficent.
Not recommended for public use; see the Stencil class documentation for examples of how to build a Stencil with Shift - coefficient syntax.
Parameters
a_shift Shift of this operation
a_coef Coefficient of this operation
a_destRefratio (Optional) Destination refinement ratio. Defaults to (1,...,1) (no refinement)
a_destShift (Optional) Destination shift. Defaults to (0,...,0) (no shift)
a_srcRefratio (Optional) Source refinement ratio. Defaults to (1,...,1) (no refinement)
template<typename T> Stencil< T > Proto::Stencil< T >::operator* (const Stencil< T > & a_stencil) const
Stencil Composition.
The product of two Stencils is defined as the composition of the two.
Parameters
a_stencil Another Stencil
template<typename T> Stencil< T > Proto::Stencil< T >::operator* (const T a_coef) const
Scalar Multiplication.
The product of a Stencil S and a coefficient v of type T results in the scaling of all the coefficients of S by v.
Parameters
a_coef Scaling coefficient
template<typename T> void Proto::Stencil< T >::operator*= (const Stencil< T > & a_stencil)
In Place Stencil Composition.
Parameters
a_stencil Another Stencil
References Proto::Point::Basis(), and Proto::Shift::Shift().
template<typename T> void Proto::Stencil< T >::operator*= (const T a_coef)
In Place Scalar Multiplication.
template<class T> Stencil< T > Proto::Stencil< T >::operator+ (const Stencil< T > & a_stencil) const
Stencil Addition.
Adding two Stencils results in a new Stencil which is the union of the coefficent-Shift pairs of the inputs. If the two input Stencils share a common Shift, the associated coefficients will be added together.
Parameters
a_stencil Another Stencil
template<class T> Stencil< T > Proto::Stencil< T >::operator- (const Stencil< T > & a_stencil) const
Stencil Subtraction (Convenience)
Equivalent to adding a_stencil*(-1)
Parameters
a_stencil Another Stencil
template<class T> void Proto::Stencil< T >::operator+= (const Stencil< T > & a_stencil)
In Place Stencil Addition.
Parameters
a_stencil Another Stencil
template<class T> void Proto::Stencil< T >::operator-= (const Stencil< T > & a_stencil)
In Place Stencil Subtraction.
Parameters
a_stencil Another Stencil
template<typename T> bool Proto::Stencil< T >::operator== (Stencil< T > & a_stencil) const inline
Equality Operator
Equality between Stencils is determined by value
Parameters
a_stencil Another Stencil
template<typename T> bool Proto::Stencil< T >::operator!= (Stencil< T > & a_stencil) const inline
Inquality Operator.
Parameters
a_stencil Another Stencil
template<typename T> const std::vector<T>& Proto::Stencil< T >::coefs () const inline
Get Vector of Coefficients.
Returned vector is read-only. Ordering corresponds to the output of Stencil::offsets()
template<typename T> const std::vector<Point>& Proto::Stencil< T >::offsets () const inline
Get Vector of Offsets.
Returned vector is read-only. Ordering corresponds to the output of Stencil::coefs()
template<typename T> unsigned long long int Proto::Stencil< T >::size () const inline
Size.
Defined as the number of coefficient-offset pairs in the stencil
Referenced by Proto::Stencil< double >::transpose().
template<typename T> Box Proto::Stencil< T >::span () const inline
Span.
Returns a Box which bounds all offsets in *this. Useful for automated ghost-cell checks.
Example:
//DIM = 2
using namespace Proto;
Stencil<T> S = 1.0*Shift(0,-1) +
               2.0*Shift(0,2) +
               3.0*Shift(1,3);
std::cout << S.span() << std::endl; //prints [(-1,0), (2,3)]
template<typename T> Point Proto::Stencil< T >::spanPoint () const inline
Span.
Returns the span as a Point. Useful when interested only in isotropic ghost regions. this computation will always allow for at least the correct number of ghost cells, and will overestimate in the case of non-isotropic spans.
template<typename T > unsigned long long int Proto::Stencil< T >::numFlops (const Box & a_box) const inline
template<typename T> Point Proto::Stencil< T >::ghost () const inline
Ghost.
Returns the necessary ghost region width in the form of a Point. If a Stencil requires a different number of ghost cells in the "upper" direction than the "lower" direction, the larger value will be used.
template<typename T> Point& Proto::Stencil< T >::srcRatio () inline
Get Source Refinement Ratio.
returned reference is mutable. Use this function to set the source refinement ratio of custom Stencils
template<typename T> const Point& Proto::Stencil< T >::srcRatio () const inline
Get Source Refinement Ratio (Const)
template<typename T> Point& Proto::Stencil< T >::destRatio () inline
Get Destination Refinement Ratio.
returned reference is mutable. Use this function to set the destination refinement ratio of custom Stencils
Referenced by Proto::InterpStencil< T >::close().
template<typename T> const Point& Proto::Stencil< T >::destRatio () const inline
Get Destination Refinement Ratio (Const)
template<typename T> Point& Proto::Stencil< T >::destShift () inline
Get Destination Shift.
returned reference is mutable. Use this function to set the destination shift of custom Stencils
Referenced by Proto::InterpStencil< T >::close().
template<typename T> const Point& Proto::Stencil< T >::destShift () const inline
Get Destination Shift (Const)
template<typename T> template<unsigned int C, unsigned char D, unsigned char E> LazyStencil<T,C,D,E> Proto::Stencil< T >::operator() (const BoxData< T, C, D, E > & a_src, T a_scale = 1) const inline
Operate on BoxData.
Operate *this on a BoxData. This function works in tandem with the namespace-defined operators += and |=. See the example in the description of Stencil.
Parameters
a_scr Source BoxData
a_scale (Optional) Scale the output of the Stencil operation. Useful for eliding calls to BoxData::operator*=(...) and similar.
template<typename T> template<unsigned int C, unsigned char D, unsigned char E> LazyStencil<T,C,D,E> Proto::Stencil< T >::operator() (const BoxData< T, C, D, E > & a_src, Box a_box, T a_scale = 1) const inline
Operate on BoxData (Overload with Box Input)
Operate *this on a BoxData. This function works in tandem with the namespace-defined operators += and |=. See the example in the description of Stencil.
Parameters
a_scr Source BoxData
a_box Confinement Box. Must be a subset of the allowable range of *this
a_scale (Optional) Scale the output of the Stencil operation. Useful for eliding calls to BoxData::operator*=(...) and similar.
template<typename T> void Proto::Stencil< T >::transpose (unsigned char a, unsigned char b) inline
Transpose Stencil.
Transposes *this across two directions in [0,DIM). After transpose, coefficients associated with the offset (a,...,b,...) will be associated instead with (b,...,a,...)
template<typename T> Box Proto::Stencil< T >::indexRange (Box a_domain) const inline
Get Max Index Range.
Given a domain, compute the largest possible iteration Box, taking source/ destination refinement into account. For Stencils without source or destination refinement, this function is identical to Stencil::range.
Parameters
a_domain A computational domain
Referenced by Proto::Stencil< double >::indexRange(), Proto::Stencil< double >::operator()(), and Proto::Stencil< double >::range().
template<typename T> Box Proto::Stencil< T >::indexDomain (Box a_range) const inline
Get Max Index Domain.
Given a domain, compute the largest possible iteration Box, taking source / destination refinement into account. The output of this function is always a valid input for a Stencil operation. For Stencils without source or destination refinement, this function is identical to Stencil::domain.
Parameters
a_range A computational range
Referenced by Proto::Stencil< double >::domain(), and Proto::Stencil< double >::indexDomain().
template<typename T> Box Proto::Stencil< T >::range (Box a_domain) const inline
Get Max Range Box.
Given a domain, compute the largest associated physical range, taking refinement AND destination shifting into account. The output of this function is NOT a valid input for a Stencil operation when refinement is present. This function is best used for defining output BoxData when the input domain is known.
Parameters
a_domain A computational domain
Referenced by Proto::Stencil< double >::range().
template<typename T> Box Proto::Stencil< T >::domain (Box a_range) const inline
Get Min Domain Box.
Given a range, compute the smallest associated physical domain, taking refinement AND destination shifting into account. The output of this function is NOT a valid input for a Stencil operation when refinement is present. Thisfunction is best used for defining input BoxData when the output range is known.
Parameters
a_range A computational range
Referenced by Proto::Stencil< double >::domain().
template<typename T> void Proto::Stencil< T >::print () const inline
Print.
Print *this to the command line. Useful for debugging.
template<typename T> template<unsigned int C, unsigned char D, unsigned char E> void Proto::Stencil< T >::apply (const BoxData< T, C, D, E > & a_src, BoxData< T, C, D, E > & a_dest, const Box & a_bx, bool a_initToZero = false, const T a_scale = 1) const
Apply Stencil Helper function.
Manually appy *this to a source and destination BoxData in a functional programming style. Not recommended for public use, but useful for debugging in some cases.
Parameters
a_src Source data
a_dest Output data
a_bx Iteration box for this computation. Can be created with indexDomain or indexRange functions.
a_replace (Optional) If true, zero out the data in a_dest and replace with the computation result. If true, solution will be added to existing data. Default false.
a_scale (Optional) Scale the computation by some value.
template<typename T > Stencil<T> Proto::operator* (T a_coef, Shift a_shift) inline
Coefficient Shift Product "Constructor".
Syntactical sugar that allows a Stencil to be constructed with coef*Shift(Point) syntax
Example:
Stencil<double> S = 3.7*Shift(Point::Basis(0));
template<typename T > Stencil<T> Proto::operator* (T a_coef, const Stencil< T > a_stencil) inline
Scalar Multiplication of Stencil Coefficients.
Allows for pre multiplication by a T scalar
template<typename T , unsigned int C, unsigned char D, unsigned char E> BoxData<T,C,D,E>& Proto::operator|= (BoxData< T, C, D, E > & a_dest, LazyStencil< T, C, D, E > && a_op) inline
Application by Replacement.
Applies a LazyStencil and replaces a subset of a_dest with the result:
Usage:
Stencil<double> S;
BoxData<double> Src;
Box computeBox;
// define S, computeBox and initialize Src
BoxData<double> Dest |= S(Src, computeBox);
See the main documentation for Stencil for additional examples
Parameters
a_dest Destination array
a_op Uncomputed Stencil operation
References PROTO_ASSERT.
template<class T , unsigned int C, unsigned char D, unsigned char E> BoxData<T,C,D,E>& Proto::operator+= (BoxData< T, C, D, E > & a_dest, LazyStencil< T, C, D, E > && a_op)
Application by Increment.
Applies a LazyStencil and replaces a subset of a_dest with the result:
Usage:
Stencil<double> S;
BoxData<double> Src;
Box computeBox;
// define S, computeBox and initialize Src
BoxData<double> Dest += S(Src, computeBox);
See the main documentation for Stencil for additional examples
Parameters
a_dest Destination array
a_op Uncomputed Stencil operation
References PROTO_ASSERT.
template<class T> Proto::InterpStencil< T >::InterpStencil (int a_ratio) inline
Isotropic Constructor.
Builds an InterpStencil assuming a destination refinement of a_ratio in all directions.
Parameters
a_ratio destination refinement
References Proto::InterpStencil< T >::define(), and Proto::Point::Ones().
template<class T> Proto::InterpStencil< T >::InterpStencil (Point a_ratio) inline
Anisotropic Constructor.
Builds an InterpStencil with a destination refinement of a_ratio;
Parameters
a_ratio destination refinement
References Proto::InterpStencil< T >::define().
template<class T> void Proto::InterpStencil< T >::define (Point a_ratio) inline
Define.
Builds an InterpStencil with a destination refinement a_ratio.
Parameters
a_ratio destination refinement
References Proto::InterpStencil< T >::m_closed, Proto::InterpStencil< T >::m_k, Proto::InterpStencil< T >::m_s, Proto::Point::Ones(), PROTO_ASSERT, and Proto::Box::size().
Referenced by Proto::InterpStencil< T >::InterpStencil().
template<class T> Stencil<T>& Proto::InterpStencil< T >::operator() (Point a_p) inline
Get Read-Write Stencil Subcomponent.
Returns a reference to the Stencil associated with the destShift a_p.
Parameters
a_p A destination shift in [(0,...,0), (destRatio-1,...,destRatio-1)]
References Proto::Box::contains(), Proto::Box::index(), Proto::InterpStencil< T >::m_closed, Proto::InterpStencil< T >::m_k, Proto::InterpStencil< T >::m_s, and PROTO_ASSERT.
template<class T> const Stencil<T>& Proto::InterpStencil< T >::get (Point a_p) const inline
Get Read-Only Stencil Subcomponent.
Returns a const reference to the Stencil associated with the destShift a_p.
Parameters
a_p A destination shift in [(0,...,0), (destRatio-1,...,destRatio-1)]
References Proto::Box::contains(), Proto::Box::index(), Proto::InterpStencil< T >::m_k, Proto::InterpStencil< T >::m_s, and PROTO_ASSERT.
template<class T> Box Proto::InterpStencil< T >::span () inline
Span.
Computes the composite span of all Stencils in the InterpStencil
References Proto::InterpStencil< T >::m_s.
Referenced by Proto::InterpStencil< T >::spanPoint().
template<class T > template<unsigned int C, unsigned char D, unsigned char E> LazyStencil< T, C, D, E > Proto::InterpStencil< T >::operator() (const BoxData< T, C, D, E > & a_src, T a_scale = 1) const inline
Lazy Apply.
Gathers inputs for the composite Stencil operation and stores them in an intermediate LazyStencil to be consumed by a left hand side operator ("=", "|=", or "+="). The syntax is intentionally identical to that used by Stencil.
Parameters
a_src Source data
a_scale (Optional) value to scale the output of *this by.
References Proto::Stencil< T >::m_destRefratio.
template<class T > template<unsigned int C, unsigned char D, unsigned char E> LazyStencil< T, C, D, E > Proto::InterpStencil< T >::operator() (const BoxData< T, C, D, E > & a_src, Box a_box, T a_scale = 1) const inline
Lazy Apply.
Gathers inputs for the composite Stencil operation and stores them in an intermediate LazyStencil to be consumed by a left hand side operator ("=", "|=", or "+="). The syntax is intentionally identical to that used by Stencil. Explicitly defining a Box input is not recommended unless absolutely necessary.
Parameters
a_src Source data
a_box Iteration box
a_scale (Optional) value to scale the output of *this by.
template<class T> Box Proto::InterpStencil< T >::kernel () const inline
Return Shift Kernel.
References Proto::InterpStencil< T >::m_k.
template<class T> Point Proto::InterpStencil< T >::ratio () const inline
Return Destination Refinement Ratio.
References Proto::InterpStencil< T >::m_r.
template<class T> std::vector<Stencil<T> >::iterator Proto::InterpStencil< T >::begin () inline
Iterate Over Stencil Components.
References Proto::InterpStencil< T >::m_s.
template<class T> std::vector<Stencil<T> >::iterator Proto::InterpStencil< T >::end () inline
Iterate Over Stencil Components.
References Proto::InterpStencil< T >::m_s.
template<class T> bool Proto::InterpStencil< T >::empty () inline
Empty Query.
References Proto::InterpStencil< T >::m_s.
template<class T> unsigned long long int Proto::InterpStencil< T >::size () const inline
Size Query.
Returns the number of Stencil components in *this.
References Proto::InterpStencil< T >::m_s.
double Proto::coarseCoef (Point p, Point s, double h) inline
References Proto::Box::high(), Proto::Box::low(), and Proto::Stencil< T >::m_span.
double Proto::fineCoef (Point p, Point s, double h, int refRatio) inline
Returns <x^p> over the fine cell s with coarse spacing h
int Proto::dgemv_ (char * , int * , int * , double * , double * , int * , double * , int * , double * , double * , int *)
int Proto::dgemm_ (char * , char * , int * , int * , int * , double * , double * , int * , double * , int * , double * , double * , int *)
int Proto::dgetri_ (int * , double * , int * , int * , double * , int * , int *)
int Proto::dgetrf_ (int * , int * , double * , int * , int * , int *)
template<typename T> void Proto::Stencil< T >::augment (T a_coef, Point a_offset) private
Augment Stencil.
Helper function that encapsulates all of the proper checks needed to add a coefficient-offset pair to a Stencil. Any new function that needs to add data to an existing Stencil should call this.
template<typename T> template<unsigned int C, unsigned char D, unsigned char E> void Proto::Stencil< T >::hostApply (const BoxData< T, C, D, E > & a_src, BoxData< T, C, D, E > & a_dest, const Box & a_box, bool a_initToZero, T a_scale) const
Variable Documentation
Point Proto::Shift::m_shift private
Referenced by Proto::Shift::operator*(), Proto::Shift::Shift(), and Proto::Shift::shift().
Friends
template<typename T> template<typename TT , unsigned int C, unsigned char D, unsigned char E> friend class BoxData friend
template<typename T> template<typename TT , unsigned int C, unsigned char D, unsigned char E> BoxData<TT,C,D,E>& operator|= (BoxData< TT, C, D, E > & a_dest, LazyStencil< TT, C, D, E > && a_op) friend
template<typename T> template<typename TT , unsigned int C, unsigned char D, unsigned char E> BoxData<TT,C,D,E>& operator+= (BoxData< TT, C, D, E > & a_dest, LazyStencil< TT, C, D, E > && a_op) friend