Proto: Proto Namespace Reference
Proto Namespace Reference
Classes
class Box
An interval in DIM dimensional space.
class BoxIterator
Iterator for Boxes.
class Stencil
A Linear Stencil Operation.
struct LazyStencil
An Unevaluated Stencil Operation.
class BoxData
Multidimensional Rectangular Array.
class CInterval
Component-Space Interval.
class Var
Pointwise Variable.
class Point
Integer Valued Vector.
class RK4
Generic Explicit RK4 Algorithm.
class Shift
Stencil Shift.
class InterpStencil
Interpolation Stencil.
class TraceTimer
class AutoStartLeaf
class AutoStart
class BaseIF
Class that specifies and implicit function.
struct EBDataLoc
class BaseEBBoxData
class EBBoxData
Holder for EB data over a box.
class EBBoxData< CELL, data_t, ncomp >
class EBBoxData< BOUNDARY, data_t, ncomp >
class EBBoxData< XFACE, data_t, ncomp >
class EBBoxData< YFACE, data_t, ncomp >
class EBBoxData< ZFACE, data_t, ncomp >
struct EBIrregStruct
class EBDictionary
class that creates and stores EBStencils
class EBFluxData
Convenience structure that holds coordinate face data in all directions.
class EBIndex
class CellNode
class EBGraph
Geometric description within a box.
class BaseEBHostData
class EBHostData
class EBHostData< CELL, data_t, ncomp >
class EBHostData< BOUNDARY, data_t, ncomp >
class EBHostData< XFACE, data_t, ncomp >
class EBHostData< YFACE, data_t, ncomp >
class EBHostData< ZFACE, data_t, ncomp >
class EBStencil
class to encapsulate evaluating a stencil for an embedded boundary calculation
class GeometryService
Makes geometric description from an implicit function.
class HostBoxData
Multidimensional Rectangular Array that lives on the host.
class Side
Encapsulation of high or low side.
class SideIterator
Iterator for low and high side.
class RealVect
A double vector in DIM-dimensional space.
class SimpleGeometry
truly simple geometries can have some simplified bits about what is all covered or regular
class SimpleEllipsoidIF
Ellipsoid.
class SimpleSphereIF
Sphere.
class AllRegularIF
class PlaneIF
Enumerations
enum CENTERING
Functions
std::ostream & operator<< (std::ostream &a_os, const Box &a_box)
OStream Operator.
void null_deleter_boxdata (void *ptr)
std::ostream & operator<< (std::ostream &a_os, const CInterval &a_int)
Print with IOStream.
template<typename Func , typename... Srcs>
void forallInPlace_i (const Func &a_F, Box a_box, Srcs &...a_srcs)
template<typename Func , typename... Srcs>
void forallInPlace_p (unsigned long long int a_num_flops_point, const char *a_timername, const Func &a_F, Box a_box, Srcs &...a_srcs)
std::ostream & operator<< (std::ostream &a_os, const Point &a_pt)
Stream Operator.
Point operator* (int a_scale, Point a_pt)
Premultiplication by scalar.
Point operator- (Point a_pt)
Unary Negation.
template<unsigned int P>
int ipow (int M)
Template Based Integer Exponentiation.
template<>
int ipow< 0 > (int M)
double coarseCoef (Point p, Point s, double h)
double fineCoef (Point p, Point s, double h, int refRatio)
int dgemv_ (char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *)
int dgemm_ (char *, char *, int *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *)
int dgetri_ (int *, double *, int *, int *, double *, int *, int *)
int dgetrf_ (int *, int *, double *, int *, int *, int *)
const char * WriteBoxData (BoxData< double > &a_array, double dx=1.0)
Write Scalar BoxData.
void WriteBoxData (const char *a_filename, BoxData< double > &a_array, double dx=1.0)
Write Scalar BoxData with Name.
template<class T , unsigned int C, unsigned char D, unsigned char E>
void WriteBoxData (const char *a_filename, BoxData< T, C, D, E > &a_array, const char *const a_varnames[C *D *E], const double *a_corner, const double &a_h)
Write Non-Scalar BoxData with Name.
template<class T , unsigned int C, unsigned char D, unsigned char E>
void WriteBoxData (FILE *a_fp, BoxData< T, C, D, E > &a_array, const char *const a_varnames[C *D *E], const double *a_corner, const double &a_h)
Write Non-Scalar BoxData to Existing File.
template<int n>
void WriteData (BoxData< double, n > &a_state, const int &a_iter, const double &a_dx, const string &a_varnamebase, const string &a_filenamebase)
template<int n>
void viewData (BoxData< double, n > *a_statePtr)
int ebp_index (int a_idir, Side::LoHiSide a_side)
Return the index into the arc vector.
template<typename Func , typename... Srcs>
void ebforallInPlace (unsigned long long int a_num_flops_point, const char *a_timername, const Func &a_F, Box a_box, Srcs &...a_srcs)
version that does not send the point to the function
template<typename Func , typename... Srcs>
void ebforallInPlace_i (unsigned long long int a_num_flops_point, const char *a_timername, const Func &a_F, Box a_box, Srcs &...a_srcs)
version that sends the point to the function
template<typename Func , typename... Srcs>
void ebforallIrreg (const char *a_timername, const Func &a_F, Box a_box, Srcs &...a_srcs)
version that only touches cut cells
template<typename Func , typename... Srcs>
void ebforallIrreg_i (const char *a_timername, const Func &a_F, Box a_box, Srcs &...a_srcs)
version that only touches cut cells
template<CENTERING dstCent, CENTERING srcCent>
EBIndex< dstCent > getEBIndex (const EBIndex< srcCent > &a_src)
template<CENTERING cent>
vector< EBIndex< cent > > getIrregFaces (const Box &a_box, const EBGraph &a_graph)
template<>
vector< EBIndex< XFACE > > getIrregFaces (const Box &a_box, const EBGraph &a_graph)
template<>
vector< EBIndex< YFACE > > getIrregFaces (const Box &a_box, const EBGraph &a_graph)
template<CENTERING cent>
vector< EBIndex< cent > > getSideFaces (const EBIndex< CELL > a_vof, Side::LoHiSide a_sd, const EBGraph &a_graph)
template<>
vector< EBIndex< XFACE > > getSideFaces (const EBIndex< CELL > a_vof, Side::LoHiSide a_sd, const EBGraph &a_graph)
template<>
vector< EBIndex< YFACE > > getSideFaces (const EBIndex< CELL > a_vof, Side::LoHiSide a_sd, const EBGraph &a_graph)
int sign (const Side::LoHiSide &a_side)
Side::LoHiSide flip (const Side::LoHiSide &a_side)
RealVect BASISREALV (int idir)
void convertToITM (IndexTM< double, DIM > &a_itmpoint, const RealVect &a_rvpoint)
Alias and Slice Operators
The alias and slice operations facilitate BoxData operations while avoiding unnecessary copies. See the sample code below for an explanation of the syntax.
Example alias usage:
Example slice usage:
template<class T , unsigned int C = 1, unsigned char D = 1, unsigned char E = 1>
BoxData< T, C, D, E > alias (BoxData< T, C, D, E > &a_original, const Point &shift=Point::Zeros())
Alias (Non-Const)
template<class T , unsigned int C = 1, unsigned char D = 1, unsigned char E = 1>
const BoxData< T, C, D, E > alias (const BoxData< T, C, D, E > &a_original, const Point &shift=Point::Zeros())
Alias (Const)
template<typename T , unsigned int C, unsigned char D, unsigned char E>
BoxData< T > slice (const BoxData< T, C, D, E > &a_src, unsigned int a_c, unsigned int a_d=0, unsigned int a_e=0)
Slice Arbitrary Component (Non-Const)
Pointwise Operators
The suite of forall functions facilitate writing functions that operate pointwise on BoxData. To this end, the user must write a function with one of the following structures:
PROTO_KERNEL_START
void F_temp(Var<T,C,D,E>&, Args...)
{ ... }
PROTO_KERNEL_END(F_temp, F)
// OR
PROTO_KERNEL_START
void F_p_temp(Point&, Var<T,C,D,E>&, Args...)
{ ... }
PROTO_KERNEL_END(F_p_temp, F_p)
PROTO_KERNEL_START and PROTO_KERNEL_END are required for cross-platform (e.g. GPU compatable) code.
The "#_temp" symbols are temporaries; the actual function symbol is the one without "_temp"
The template arguments of the first Var argument must match the output BoxData
The Point argument in the second signature corresponds to the Point of function application
Args... may include any number of Var& or read-only scalars.
The elements of Args... may have arbitrary tensor structure and const-ness
non-const objects in Args... have input-output semantics
The order and template arguments of the Vars in Args... must match the BoxData inputs of forall
If F is a member function of a class F MUST BE DECLARED STATIC
F or F_p may be an anonymous (lambda) function defined using the PROTO_LAMBDA macro
Refer to the following code snippet for some sample valid forall input functions:
template<typename T , unsigned int C = 1, unsigned char D = 1, unsigned char E = 1, typename Func , typename... Srcs>
BoxData< T, C, D, E > forall (const Func &a_F, Srcs &...a_srcs)
Pointwise Operator.
template<typename T , unsigned int C = 1, unsigned char D = 1, unsigned char E = 1, typename Func , typename... Srcs>
BoxData< T, C, D, E > forallOp (unsigned long long int a_num_flops_point, const char *a_timername, const Func &a_F, Srcs &...a_srcs)
same idea, but with flop counts and a timer name
template<typename T , unsigned int C = 1, unsigned char D = 1, unsigned char E = 1, typename Func , typename... Srcs>
BoxData< T, C, D, E > forall (const Func &a_F, Box a_box, Srcs &...a_srcs)
Pointwise Operator: Overload with Box Argument.
template<typename T , unsigned int C = 1, unsigned char D = 1, unsigned char E = 1, typename Func , typename... Srcs>
BoxData< T, C, D, E > forallOp (unsigned long long int a_num_flops_point, const char *a_timername, const Func &a_F, Box a_box, Srcs &...a_srcs)
same idea, but with flop counts and a timer name
template<typename T , unsigned int C = 1, unsigned char D = 1, unsigned char E = 1, typename Func , typename... Srcs>
BoxData< T, C, D, E > forall_p (const Func &a_F, Srcs &...a_srcs)
Pointwise Operator with Point Dependence.
template<typename T , unsigned int C = 1, unsigned char D = 1, unsigned char E = 1, typename Func , typename... Srcs>
BoxData< T, C, D, E > forall_p (const Func &a_F, Box a_box, Srcs &...a_srcs)
Pointwise Operator with Point Dependence: Overload with const Box Argument.
template<typename Func , typename... Srcs>
void forallInPlace (const Func &a_F, Srcs &...a_srcs)
In-Place Pointwise Operator.
template<typename Func , typename... Srcs>
void forallInPlace (const Func &a_F, Box a_box, Srcs &...a_srcs)
In-Place Pointwise Operator on Prescribed Box.
template<typename Func , typename... Srcs>
void forallInPlace_p (const Func &a_F, Srcs &...a_srcs)
In-Place Pointwise Operator with Point Dependence.
template<typename Func , typename... Srcs>
void forallInPlace_p (const Func &a_F, Box a_box, Srcs &...a_srcs)
In-Place Pointwise Operator with Point Dependence and Prescribed Box.
Non-Member Functions
template<typename T >
Stencil< T > operator* (T a_coef, Shift a_shift)
Coefficient Shift Product "Constructor".
template<typename T >
Stencil< T > operator* (T a_coef, const Stencil< T > a_stencil)
Scalar Multiplication of Stencil Coefficients.
template<typename T , unsigned int C, unsigned char D, unsigned char E>
BoxData< T, C, D, E > & operator|= (BoxData< T, C, D, E > &a_dest, LazyStencil< T, C, D, E > &&a_op)
Application by Replacement.
template<class T , unsigned int C, unsigned char D, unsigned char E>
BoxData< T, C, D, E > & operator+= (BoxData< T, C, D, E > &a_dest, LazyStencil< T, C, D, E > &&a_op)
Application by Increment.
Detailed Description
TraceTimer class is a self-tracing code instrumentation system
TraceTimer class is a self-tracing code instrumentation system for Chombo (or any other package really). The user interface is specified by a small set of macros. The usage model is that you just leave these timers in the code, for good. Initially, your application will have 'main' and a few hewavy functions instrumented, and the lower level Chombo library instrumentation. As your tool or application matures, it will garner a larger set of instrumentation giving clear views of your code performance. After a routine has been cleverly and lovingly optimized, you leave in the timers, to spot when some later bug fix or improvement undoes your previous labors.
Note
You should never need to use or interact with the the classes TraceTimer or AutoStart. Use the macros. They call the right functions and classes for you.
The first macro is what people will use the most:
PR_TIME("label");
This is the simplest interface for timers. you place this macro call in a function you wish to be timed. It handles making the timer, calling 'start' when you enter the function, and calling 'stop' when you leave the function. A good idea is to use a 'label' specific enough to be unambiguous without being overwhelming. for instance:
void AMRLevelPolytropicGas::define(AMRLevel*            a_coarserLevelPtr,
const ProblemDomain& a_problemDomain,
int                  a_level,
int                  a_refRatio)
{
PR_TIME("AMRLevelPolytropicGas::define");
.
.
}
In this case, we have a class with many constructors and define functions that all funnel into a single general function. We can just call this 'define' and not worry about naming/instrumenting all the different overloaded instances. If you slip up and use the same label twice, that is not a real problem, the two locations will be timed and tracked properly (even if one is a sibling or parent of the other). The only place it will make things a little harder is in the output where you might have the same name show up and look confusing.
In serial, you will see a file called time.table (in parallel, you will get a time.table.n (where n is the rank number) files). If you want fewer files, you can do setenv PR_OUTPUT_INTERVAL nproc and it will only output every nproc processors time.table.n files (where nnproc == 0). I won't go into this file format. It is kind of gprof-ish, with what I consider improvements. The real benefit here is profiling that understands our Chombo context, a smaller information set to observe, and the fact that, so far in my testing, the timers have negligible impact on the run time or memory use of the code.
By default, Chombo compiles in the instructions for the timers wherever the macros appear. If the compiler macro PR_NTIMER is defined, then all the PR_TIME* macros evaluate to empty expressions at compile time.
So, you put some PR_TIME calls in your code and ran it, and nothing happened:
Chombo looks for the environment variable PR_TIMER. If it is set to anything (even if it is set to 'false' or 'no' or whatever) then the timers will be active and reporting will happen. If this environment variable is not set, then all the timers check a bool and return after doing nothing.
One point of interest with using the environment variable: In parallel jobs using mpich, only processor 0 inherits the environment variables from the shell where you invoke 'mpirun', the rest read your .cshrc (.bashrc, etc.) file to get their environment. To time all your processes, you need to make sure the PR_TIMER environment variable gets to all your processes.
Auto hierarchy:
The timers automatically figure out their parent/child relationships. They also can be placed in template code. This has some consequences. First, if you have a low level function instrumented that has no timers near it in the code call stack, you will see it show up as a child of a high level timer. the root timer "main" will catch all orphaned timers. So, even though you might make no call to, say, 'exchange' in your 'main' function, you might very well call a function, that calls a function, that calls 'exchange'. Since no code in between was instrumented, this exchange is accounted for at 'main'. This might look strange, but it should prove very powerful. An expensive orphan is exactly where you should consider some more timers, or reconsidering code design.
For performance reasons, child timers have only one parent. As a consequence each PR_TIME("label") label can show up at multiple places in your output. Each instance has it's own timer. So, each path through the call graph that arrives at a low-level function has a unique lineage, with it's own counter and time. Thus, I can instrument LevelData::copyTo once, but copyTo can appear in many places in the time.table file.
The next level up in complexity is the set of four macros for when you want sub-function resolution in your timers. For instance, in a really huge function that you have not figured out how to re-factor, or built with lots of bad cut n paste code 're-use'.
PR_TIMERS("parent");
PR_TIMER("child1", t1);
PR_TIMER("child2", t2);
PR_START(t1);
PR_STOP(t1);
PR_START(t2);
PR_STOP(t2);
PR_START(t1);
PR_STOP(t1);
PR_TIMERS has the same semantic as PR_TIME, except that you can declare an arbitrary number of children after it in the same function scope. The children here do not autostart and autostop, you have to tell them where to start and stop timing. The children can themselves be parents for timers in called functions, of course. The children obey a set of mutual exclusions. The following generate run time errors:
double start called
double stop called
start called when another child is also started
you leave the function with a child not stopped
the following will generate compile time errors:
more than one PR_TIME macro in a function
invoking PR_TIMER("child", t) without having first invoked PR_TIMERS
re-using the timer handle ie. PR_TIMER("bobby", t1); PR_TIMER("sally", t1)
mixing PR_TIME macro with PR_TIMER
mixing PR_TIME macro with PR_TIMERS
You do not have to put any calls in your main routine to activate the clocks or generate a report at completion, this is handled with static iniitalization and an atexit function.
There is a larger argument of manual instrumentation being counter to good development. Profiling the code is supposed to tell you where to expend your optimization effort. Manual instrumentation opens the door to people wasting time assuming what parts of the code are going to take up lots of time and instrumenting them, before seeing any real performance data. Good judgement is needed. We have a body of knowledge about Chombo that will inform us about a good minimal first set of functions to instrument.
Enumeration Type Documentation
enum Proto::CENTERING
Function Documentation
std::ostream& Proto::operator<< (std::ostream & a_os, const Box & a_box) inline
OStream Operator.
References Proto::Box::high(), and Proto::Box::low().
void Proto::null_deleter_boxdata (void * ptr) inline
template<typename Func , typename... Srcs> void Proto::forallInPlace_i (const Func & a_F, Box a_box, Srcs &... a_srcs)
template<typename Func , typename... Srcs> void Proto::forallInPlace_p (unsigned long long int a_num_flops_point, const char * a_timername, const Func & a_F, Box a_box, Srcs &... a_srcs) inline
std::ostream& Proto::operator<< (std::ostream & a_os, const Point & a_pt) inline
Stream Operator.
Point Proto::operator* (int a_scale, Point a_pt) inline
Premultiplication by scalar.
Point Proto::operator- (Point a_pt) inline
Unary Negation.
template<unsigned int P> int Proto::ipow (int M) inline
Template Based Integer Exponentiation.
template<> int Proto::ipow< 0 > (int M) inline
template<int n> void Proto::WriteData (BoxData< double, n > & a_state, const int & a_iter, const double & a_dx, const string & a_varnamebase, const string & a_filenamebase) inline
References WriteBoxData().
template<int n> void Proto::viewData (BoxData< double, n > * a_statePtr) inline
int Proto::ebp_index (int a_idir, Side::LoHiSide a_side) inline
Return the index into the arc vector.
template<typename Func , typename... Srcs> void Proto::ebforallInPlace (unsigned long long int a_num_flops_point, const char * a_timername, const Func & a_F, Box a_box, Srcs &... a_srcs) inline
version that does not send the point to the function
References PR_FLOPS, PR_TIME, and Proto::Box::size().
template<typename Func , typename... Srcs> void Proto::ebforallInPlace_i (unsigned long long int a_num_flops_point, const char * a_timername, const Func & a_F, Box a_box, Srcs &... a_srcs) inline
version that sends the point to the function
References PR_FLOPS, PR_TIME, and Proto::Box::size().
template<typename Func , typename... Srcs> void Proto::ebforallIrreg (const char * a_timername, const Func & a_F, Box a_box, Srcs &... a_srcs) inline
version that only touches cut cells
References PR_TIME.
template<typename Func , typename... Srcs> void Proto::ebforallIrreg_i (const char * a_timername, const Func & a_F, Box a_box, Srcs &... a_srcs) inline
version that only touches cut cells
References PR_TIME.
template<CENTERING dstCent, CENTERING srcCent> EBIndex<dstCent> Proto::getEBIndex (const EBIndex< srcCent > & a_src)
template<CENTERING cent> vector<EBIndex<cent> > Proto::getIrregFaces (const Box & a_box, const EBGraph & a_graph) inline
References Proto::EBGraph::getIrregXFaces(), and Proto::EBGraph::getIrregYFaces().
template<> vector<EBIndex<XFACE> > Proto::getIrregFaces (const Box & a_box, const EBGraph & a_graph) inline
References Proto::EBGraph::getIrregXFaces().
template<> vector<EBIndex<YFACE> > Proto::getIrregFaces (const Box & a_box, const EBGraph & a_graph) inline
References Proto::EBGraph::getIrregYFaces().
template<CENTERING cent> vector<EBIndex<cent> > Proto::getSideFaces (const EBIndex< CELL > a_vof, Side::LoHiSide a_sd, const EBGraph & a_graph) inline
References Proto::EBGraph::getXFaces(), and Proto::EBGraph::getYFaces().
template<> vector<EBIndex<XFACE> > Proto::getSideFaces (const EBIndex< CELL > a_vof, Side::LoHiSide a_sd, const EBGraph & a_graph) inline
References Proto::EBGraph::getXFaces().
template<> vector<EBIndex<YFACE> > Proto::getSideFaces (const EBIndex< CELL > a_vof, Side::LoHiSide a_sd, const EBGraph & a_graph) inline
References Proto::EBGraph::getYFaces().
int Proto::sign (const Side::LoHiSide & a_side) inline
References Proto::Side::Lo.
Side::LoHiSide Proto::flip (const Side::LoHiSide & a_side) inline
References Proto::Side::Hi, and Proto::Side::Lo.
RealVect Proto::BASISREALV (int idir) inline
References Proto::RealVect::Zero().
void Proto::convertToITM (IndexTM< double, DIM > & a_itmpoint, const RealVect & a_rvpoint) inline